### ISSUE TITLE
IEEE 1394 (Firewire) Support

### ISSUE THREAD

**Issue by biorpg** [ufrisk/pcileech#101]
Do you plan to support Firewire for remote memory capture? I had spent the last week or so trying to set up remote capture between two Windows machines, and had just found the answer (Unibrain FireAPI) when a friend sent me a link to pcileech. I can't imagine it would be difficult to implement, as it still possesses the native capability of DMA read without the host/target's participation just as it always has. Although on Windows, a gimp driver is installed by default (Point Grey Research/Texas Instruments) the legacy OHCI1394 driver is still available to be installed. I would, however, take a look at Unibrain's FireAPI driver, as it is more capable than a standard firewire driver. I think the non-pro edition can be redistributed, but I'm not certain.

**Comment by ufrisk** [comment]
I currently have no plans to add firewire support myself. Main reasons for this decision is:
- It's not very common nowdays
- It's only able to access memory <4GB
- systems that do have firewire most often do have PCIe as well.
- and most importantly it will take quite a bit of work for me to add this.

Now I'd love to accept a pull request with a new supported "firewire device" to the LeechCore project provided you wish to code a "device" plugin for it.
