### ISSUE TITLE
Is it possible to use pcileech when X.M.P. is enabled?

### ISSUE THREAD

**Issue by gcakir** [ufrisk/pcileech#105]
Hello,
I am unable to use pcileech when X.M.P. (Intel Extreme Memory Profile, i.e. memory overclocking) is enabled. The device I am using is PCIeScreamer.
1.) Is it possible to use without an issue when X.M.P is enabled?
2.) Is SP605 more stable to use when X.M.P. is enabled?
3.) Is there any future implementations plans to make it stable with XMP enabled?

**Comment by ufrisk** [comment]
I have not investigated this myself, but, I see no reason why XMP should change anything at all with regards to stability for DMA devices.

The PCIeScreamer R01 is known to have stability problems though. The R02 version is much better, but not as perfect as the SP605.

**Comment by gcakir** [comment]
Thank you very much for your reply. I played around with timings and frequency settings of my RAM modules. Frequency-wise, PCIeScreamer will fail to read no matter what when the frequency is set beyond 2266 MHz. But with the advertised timings (CL 14, i.e. 14-14-14-34) of the RAM modules, PCIeScreamer can read without issue. So, the frequency seem to be an issue, at least in my case. Maybe, the motherboard might be the culprit. I am not sure. I will also test with SP605 and report back.

**Comment by ufrisk** [comment]
Thanks for the update. This is very interesting. Since the PCIeScreamer is known to be somewhat unstable the SP605 results are super interesting. Also I suspect you have not tried to overclock PCIe in any way?

**Comment by gcakir** [comment]
I have discovered something interesting. When XMP (memory overclocking) is enabled, the cards will fail to read and write. I tried with both PCIeScreamer and SP605. In both, I experienced the same issue. Instead of enabling XMP, I entered the RAM module's timings and the frequency manually in BIOS. That solved all the problems in my case. Enabling XMP changes something else in BIOS settings that is not visible in the user interface (to the user). This should not happen. Similar stuff happened me back when I was using other manufacturers' products. I really dislike how companies cannot get BIOS right. There is always some annoying issue.

**Comment by ufrisk** [comment]
I don't know if this is the issue, but I've seen in some computer settings to overclock PCIe as well. I have no idea if that is the issue here - but if your BIOS would do such a thing all devices might not like it. It may be an explanation for your issue. Also thanks for the update.
