### ISSUE TITLE
pcileech on LambdaConcept R01 board crashes system 

### ISSUE THREAD

**Issue by asbridge** [ufrisk/pcileech#108]
Dear Ulf,

I'm hoping you can help me.  I am trying to use a LambdaConcept R01.

I have your 3.2 gateware file programmed.

When I try any command, such as:

./pcileech dump -min 0x0 -max 0x21e5fffff

or

./pcileech probe

My machine crashes.  Here's a snippet from the crash:

[ 5570.832140] {1}[Hardware Error]: Hardware error from APEI Generic Hardware Error Source: 1
[ 5570.832222] {1}[Hardware Error]: event severity: fatal
[ 5570.832265] {1}[Hardware Error]:  Error 0, type: fatal
[ 5570.832308] {1}[Hardware Error]:   section_type: PCIe error
[ 5570.832352] {1}[Hardware Error]:   port_type: 4, root port
[ 5570.832396] {1}[Hardware Error]:   version: 1.16
[ 5570.832436] {1}[Hardware Error]:   command: 0x4010, status: 0x0547
[ 5570.832486] {1}[Hardware Error]:   device_id: 0000:0d:00.0
[ 5570.832530] {1}[Hardware Error]:   slot: 0
[ 5570.832564] {1}[Hardware Error]:   secondary_bus: 0x0e
[ 5570.832605] {1}[Hardware Error]:   vendor_id: 0x1000, device_id: 0xc012
[ 5570.832657] {1}[Hardware Error]:   class_code: 000406
[ 5570.832699] {1}[Hardware Error]:   bridge: secondary_status: 0x0000, control: 0x0003
[ 5570.832758] {1}[Hardware Error]:  Error 1, type: fatal
[ 5570.832800] {1}[Hardware Error]:   section_type: PCIe error
[ 5570.832844] {1}[Hardware Error]:   port_type: 4, root port
[ 5570.832889] {1}[Hardware Error]:   version: 1.16
[ 5570.832926] {1}[Hardware Error]:   command: 0x4010, status: 0x0547
[ 5570.832976] {1}[Hardware Error]:   device_id: 0000:00:03.0
[ 5570.833020] {1}[Hardware Error]:   slot: 0
[ 5570.833054] {1}[Hardware Error]:   secondary_bus: 0x06
[ 5570.833095] {1}[Hardware Error]:   vendor_id: 0x8086, device_id: 0x3c08
[ 5570.833147] {1}[Hardware Error]:   class_code: 000406
[ 5570.833188] {1}[Hardware Error]:   bridge: secondary_status: 0x6000, control: 0x0003

**Comment by asbridge** [comment]
Debugging by reading these issues, I tried:

./pcileech  -v -vv -device fpga display -min 0x1000

[+] using FTDI device: 0403:601f (bus 1, device 4)
[+] FTDI - FTDI SuperSpeed-FIFO Bridge - serialNumber 000000000001
DEVICE: FPGA: SP605 / FT601 PCIe gen1 x1 [400,175,500] [v0.0,0e00]

----- FPGA DEVICE CONFIG REGISTERS: PCIE-READ-ONLY     SIZE: 0 BYTES -----

----- FPGA DEVICE CONFIG REGISTERS: PCIE-READ-WRITE    SIZE: 0 BYTES -----

The output seems totally wrong.

Does this mean the card did not program correctly?

**Comment by ufrisk** [comment]
Unfortunately the R01 version of the PCIeScreamer may experience hardware-based instabilities of a varying degree on different systems. You can try it in a different slot and see if it works better, but since the instabilities are hardware based there isn't anything I'm able to do about it. I also no longer officially supports the PCIeScreamer R01 in my project (I still provide the bitstream for it though).

With that being said I also agree that the output from the version info prompt does not look correct. Since vendor_id: 0x1000, device_id: 0xc012 does not belong to my stock bitstream I suggest you flash my stock one and retry. Quite often putting fake values in various fields may lead to crashing on some computer models.

**Comment by asbridge** [comment]
Thanks.

Could you just send me a pointer to the exact file that I should load to the card?

I used:

-rwxr--r--. 1 root      root       261513 Nov 13 18:25 bscan_spi_xc7a35t.bit
-rw-r--r--. 1 365201618 365200513     377 Feb  5  2018 flash_screamer.cfg
-rwxr--r--. 1 365201618 365200513  350764 Nov 12 17:23 pcileech_pciescreamer_3_2_bin.zip  <- From here
-rw-r--r--. 1 365201618 365200513 1512368 Mar 14  2018 pcileech_pciescreamer_top.bin <-This binary

With this command:

openocd -f flash_screamer.cfg

After flashing, my card shows up as:

lspci|grep Xilinx
0e:00.0 Ethernet controller: Xilinx Corporation Device 0666 (rev 02)

I am very willing to buy a Rev 02 of the LamdaConcept card, but will it solve my issue?

Ultimately, here is what I am trying to do:

Send VDM (Vendor Defined Message) from USB side to PCIe side to an NVMe drive for the purpose of testing the VDM support of the NVMe drive.  I need to have the FPGA card receive the VDM reply from the drive and pass it back to me via USB.

Have you ever successfully accomplished something like this?

Do you have an example?

Will the Rev02 LamdaConcept card work for this application?

Is there a better card (like the NeTV2)?  I would rather use USB because I have a spare port on my test platform, but if I have to do network I will.

I am willing to pay you for consulting if this turns into real work.

I appreciate your work on PCILeech and your prompt reply to my problem.

Vince Asbridge
SANBlaze Technology, Inc.

**Comment by asbridge** [comment]
Ulf,

I have ordered the R02 version of the SlotScreamer.  I will try again when it comes in.

Thanks, Vince

**Comment by ufrisk** [comment]
Thanks for the update, I hope it will be more stable than the R01. Please let me know if you still have trouble with the new one.

**Comment by ufrisk** [comment]
I'm closing this issue since the R01 isn't really supported officially anymore.

**Comment by asbridge** [comment]
Received my R02 card today.  All is well.  Working.  Flashed your V4.0 image and I can read system memory.  Moving forward, thanks!  Vince
