### ISSUE TITLE
Win10 kmdload issue

### ISSUE THREAD

**Issue by zredaxz** [ufrisk/pcileech#112]
Looks like the win10_x64 and win10_x64_2 no longer works. Last time (~1 year ago) when I tried it worked just fine.
Now the win10_x64 and win10_64_2 are failing with the error below. Is there any known problem here?
pcileech dump / probe works fine.

pcileech kmdload -kmd win10_x64

KMD: Failed. Failed finding entry point.
PCILEECH: Failed to load kernel module.

pcileech kmdload -kmd win10_x64_2

MemProcFS: Failed to initialize memory process file system in call to vmm.dll!VMMDLL_Initialize
KMD: Failed initializing required MemProcFS/vmm.dll
PCILEECH: Failed to load kernel module.

**Comment by ufrisk** [comment]
are you able to read memory at all?

if not, download the latest binaries from https://github.com/ufrisk/pcileech/releases/tag/v4.4, and also the very latest `FTD3XX.dll` from ftdichip.com

Having an old version of `FTD3XX.dll` may result in failed reads.

Also, it's working (most often, some times blue screen) on latest 1909 windows.

**Comment by zredaxz** [comment]
The most recent FTD3XX.dll is used (ver. 1.3.0.2) and I tried with pcileech version 4.1 and 4.4. Same result.

The 'pcileech dump' and 'pcileech probe' works fine so yes the memory reading works as expected.

**Comment by ufrisk** [comment]
and you unzipped all binaries (.dlls) in the releases file?

also, make sure your Windows does not have virtualization based security enabled, if it have kernel code integrity enabled together with hyper-v etc. the kernel injects won't work since Windows protects executable kernel memory against writes if the VT-d feature is enabled in bios and Hyper-V is running.

**Comment by zredaxz** [comment]
Yes everything is unzipped expect the USB3380Flash.zip. I guess I don't need that. Super weird.

**Comment by popalltheshells** [comment]
Hi guys, have you solve this issue? I'm using PCILeech 4.17 but still having the same error:
KMD: Failed initializing required MemProcFS/vmm.dll #1

**Comment by popalltheshells** [comment]
@ufrisk Thank you-  it was actually because of an unstable PCIe connection. Once I screwed it on completely; it worked flawlessly.
