### ISSUE TITLE
[Question] Hardware recommendation

### ISSUE THREAD

**Issue by ysovv** [ufrisk/pcileech#117]
I'm new to this and have been reading through the issues section and some external sources that some hardware are not stable. Which hardware is the most stable considering all factors (FPGA / USB3)? Thanks for the great work :+1:

**Comment by ufrisk** [comment]
Apologies for the late answer.

Overall I'd say the ScreamerM2 is the best right now. It's not working on all hardwares though for some unknown reason, but when it does it's stable and very nice.

It's sold out last I checked due to the corona though. I think the plan is to restock ASAP.

**Comment by ysovv** [comment]
Thx for the reply Ulf. In my research most users seemed to be using SP605/FT601. I ordered it yesterday. Are there any downsides for this? Thank you
