### ISSUE TITLE
Attacking over Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by meriniamjo** [ufrisk/pcileech#12]
Hi there,

I am trying to work on PCILeech, the attacker system is Windows 10 x64, and the victim system is Ubuntu 14.04 LTS (kernel version: 3.19.0-43-generic, 16-GB RAM). The card is working fine and was flashed successfully. Still, there are some issues that need to be addressed. 

1)- In the Native DMA mode, when I try to do "pcileech.exe dump" it starts to dump the memory files into a .RAW file but stops as it reaches 87% and the address at which it stops is always 0xDF000000.

![nativedma](https://cloud.githubusercontent.com/assets/15684232/19658516/441755a4-99f6-11e6-84f5-f5435b79a360.jpg)

2)- For dumping more than 4GB or memory, we need to load the kernel KMD. I tried doing it and the kernel was successfully loaded at some address into the victim. But when I again try to do the dump using KMD and that address it gets stuck at like 5%.

3)- The actual task that I want to perform is to get the memory snapshot (basically read the memory contents) and determine whether the data is changed or not. For that (from my understanding), I need to read the dump (.RAW) file having memory data. Do you have any idea how to read the .RAW files to mark down the changed memory territories.

Furthermore, the command for file pulling is working fine 
"pcileech.exe lx64_filepull -kmd LINUX_X64 -s /etc/shadow -out c:\temp\shadow".
the command for pagedisplay, testmemread, testmemreadwrite, etc. all are working fine. 

Waiting for your response. 

Thanks =)

**Comment by ufrisk** [comment]
Hi,

1) It works this way. Memory is not mapped into the memory space contiguously. The "memory" just below 4GB isn't memory at all; it's memory mapped PCIe devices or nothing at all. It is normal that the native memory dump fail here.

2) It should not be this way. I assume it's not an issue with a full disk or slow network connection to where the dump file is written. What command are you running? `pcileech kmdload -kmd linux_x64` and then `pcileech dump -kmd [addr_given_by_kmdload]`? If dumping freezes can you please check if the pcileech kernel thread is still running by typing `ps aux |grep pcileech`? Also if there is a kernel error/stack trace by typing the command `dmesg`? Also if you could re-insert the pcileech device and run the command `pcileech pagedisplay -min [addr_given_by_kmdload]` after the freeze occured.

3) You can use volatility to read the dump (.raw) files. In order for volatility to be able to interpret the files you need to create a volatility profile for your kernel version. Volatility has some information about how to do this. For some basic tasks you could also use a hexeditor on the dump itself too.

**Comment by meriniamjo** [comment]
2) Yes the commands are correct. For pcileech kmdload -kmd linux_x64  : 
![kmdload](https://cloud.githubusercontent.com/assets/15684232/19664779/02502b90-9a10-11e6-9573-23d32e9eb35b.jpg)
 
For  pcileech dump -kmd 0x6e337000
![dumpstuck](https://cloud.githubusercontent.com/assets/15684232/19664820/37157754-9a10-11e6-9e49-f3560af5620c.JPG)

When I checked if the kernel thread is still running (ps aux |grep pcileech) nothing happened. 

After re-inserting the card and checking the command pagedisplay at the module address, page reading failed.
But I tried again after rebooting the system ( From kernal load to dumping using kmd ), Page display worked fine but the dump command was still stuck. Moreover, ps aux |grep pcileech didn't give any result (it just brought me to the start of the command line) nor did dmsg/dmesg work to check the trace. 

![dmesg](https://cloud.githubusercontent.com/assets/15684232/19665562/92bab0f8-9a13-11e6-9931-86e8e3679a89.JPG)

The following three images show what I got after running the page-display command:

![page1](https://cloud.githubusercontent.com/assets/15684232/19665434/f70b9a14-9a12-11e6-99cd-3ddc2c15f769.JPG)

![page2](https://cloud.githubusercontent.com/assets/15684232/19665435/fa759c22-9a12-11e6-8242-fe392809000c.JPG)

![page3](https://cloud.githubusercontent.com/assets/15684232/19665446/fd9e23ba-9a12-11e6-9793-83d05a68e694.JPG)

**Comment by ufrisk** [comment]
Hi,

Both the `ps aux|grep pcileech` and the `dmesg` commands has to be run at the linux box (not on windows) after the freeze. If something looks like a stack trace at the end of the dmesg text it's interesting. 

It might be possible to read the DMA memory buffer after the freeze without re-inserting the card. Or it might help if you re-insert it a couple of times (if lucky).

**Comment by meriniamjo** [comment]
Hello,

So there is a good news. The memory dumping using kmd mode was successful this time. I did nothing, just rebooted the system and it worked fine. The issue is you mentioned in your read me file that we can retrieve  the memory at a rate of 150 Mb/s but for my case it never went beyond 36 Mb/s. Initially from 0%-71% it was 35 mbps but after that it kept on reducing to 8 mbps. As a whole it took about half an hour to dump the whole 16 Gb. Isn't this very slow? Or is it supposed to be like that. Just curious  :) 
![dumpsuccess](https://cloud.githubusercontent.com/assets/15684232/19701326/e1f020bc-9ac8-11e6-81fa-5a5395f2bbb4.JPG)

I also ran the pagedisplay command after the dump finished and i got something like this (Rest all address showed 00's);
![newpage1](https://cloud.githubusercontent.com/assets/15684232/19701322/ddd2e4e2-9ac8-11e6-938b-87ee2cc159ad.JPG)

Secondly, yesterday I tried the same thing but the dumping got stuck at like 2% even after the reboot and today after rebooting it worked perfectly  fine and the dumping completed. Is this hardware going to behave like that all the time.  Like randomly works fine and sometimes just gets stuck. Is it some kind of an hardware issue? 

Also,  while dumping  the memory I also checked the status of the dumping by that ps aux | grep pcileech command. Sometimes  it showed the status as R and sometimes D.  So is going to D fine ? 

And also there is no stack trace when I run dmesg command.

**Comment by ufrisk** [comment]
About the speed issue; are you sure you use a USB3 cable and plugged it into a USB3 port? Connecting the PCILeech to a USB2 port will give you those kinds of speeds (thats why I'm asking). Also writing the dump file to a slow disk will reduce output speed. 9MB/s seems to be way too slow though.

If the kernel module works (i.e. if it's not crashing/freezing) it won't produce any errors in dmesg; so that's normal. Also it's normal for the kernel thread to alternate between running and sleep (D-state). If not accessed for 5 seconds it will go to sleep short periods of time checking for new input more unfrequently to save CPU on the target system.

The hardware works fine on most computers; but I know that some systems do have problems with it.

**Comment by meriniamjo** [comment]
Yes you are right, I didn't realize USB 2.0 would create so much trouble. I was using a USB 2.0 cable. Now it makes sense for the slow speed. 

I have ordered a USB 3.0 cable, as soon as I get it I will try it and let you know.

Thanks for the help and support :)

**Comment by ufrisk** [comment]
Thanks for letting me know. Please let me know if you still have troubles once you manage to connect it over USB3.

**Comment by meriniamjo** [comment]
Hi there,

I tried dumping the memory using the USB 3.0 but I was getting a speed of 34 MB/s and the whole 16GB dump took about 10 mins. I tried doing the same thing on another laptop and it was giving me a speed around 135MB/s and the whole 16 GB dump was completed in like 2 mins. I found out that the second laptop had SSD and the first one had just a simple hard drive. Anyhow, everything is working fine now. Thanks a lot for your help :-)

If you don't mind I have one more question, Can you tell me is PCILeech manipulating the operating system to get access to the page tables ? Like can I get access to the LINUX system's (victim) pagetable contents using PCILeech ?
For example, we use these commands to pull a file and loading a kernel module in windows 10 by targeting the page table of the ntfs.sys driver respectively;

pcileech.exe lx64_filepull -kmd LINUX_X64 -s /etc/shadow -out c:\temp\shadow
pcileech.exe kmdload -kmd win10x64_ntfs_20160329 -pt

From my understanding you have the access to the victim's operating system right ? In other words you can manipulate different OS contents including pagetables ?

**Comment by ufrisk** [comment]
Auch; thats one slow disk =/ Thanks for letting me know though. I'll close this issue in a week or so then.

I'm not manipulating the page tables in Linux. I'm able to gain kernel code execution anyway. The page tables are open for manipulation from within the kernel though. If you wish to find the page table base (CR3/PML4) for the pcileech kernel thread run `pcileech.exe wx64_pageinfo -kmd linux_x64`. (it's the only windows kernel module that will work in Linux). From there you'll get it's physical base and will be able to manually do a page table walk if you wish.

**Comment by ufrisk** [comment]
I'm closing this issue since it was resolved. USB2 cable used instead of USB3.

**Comment by merinjo** [comment]
Hi there,
Sorry for opening this issue again.
Actually at start everything was working fine. I was able to dump in the DMA native mode and was also able to do it with after loading the kernel module. Now I am having some problems;
1) When I start making a dump of Linux vicitm's 16 GB memory through the windows 10 attacker system, my Linux system gets stuck.
2) When the system gets stuck, my dumping also stops (around 40-55%) which requires me to restart the system (effectively power recycling the USB board). When the system restarts and I start making a dump after loading the kernel, the dump process again gets stuck around 10-55%. I also tried one thing, when my system gets stuck, I stopped the already stuck dumping process and starting a new one. Pcileech starts dumping the memory for some time and again gets stuck.
3) The Linux system doesn't get stuck when I dump small memory chunks giving a min max range of addresses. It only freezes when I get the dump of the whole 16 GB.
4) Some times while making these small memory dumps(I call it in a loop iterating over small chunks through a system() call using c programming) I get an error as follows in between :

"C:\cygnus\cygwin-b20\H-i586-cygwin32\bin\sh.exe: * unable to allocate heap, error 0
[main] C:\cygnus\cygwin-b20\H-i586-cygwin32\bin\sh.exe 4318 (0) sync_with_child: child 9460(0x144) died before initialization with status code 0x1
[main] sh 4318 (0) sync_with_child: * child state waiting for longjmp
Cannot fork"
5) As I told you before in the previous threads of this issue, that I used USB 3.0 and borrowed my friends system having SSD. With these things i was getting a dumping speed of 150MB/Sec but now I am.not getting that speed as well. With same apparatus : USB 3.0 + SSD now I am getting a speed of 25-35 MB/Sec.

Can you help me out with these issues and guide me what to do.

Thank you.

**Comment by meriniamjo** [comment]
Hi there,
Sorry for opening this issue again.
Actually at start everything was working fine. I was able to dump in the DMA native mode and was also able to do it with after loading the kernel module. Now I am having some problems;
1) When I start making a dump of Linux vicitm's 16 GB memory through the windows 10 attacker system, my Linux system gets stuck.
2) When the system gets stuck, my dumping also stops (around 40-55%) which requires me to restart the system (effectively power recycling the USB board). When the system restarts and I start making a dump after loading the kernel, the dump process again gets stuck around 10-55%. I also tried one thing, when my system gets stuck, I stopped the already stuck dumping process and starting a new one. Pcileech starts dumping the memory for some time and again gets stuck.
3) The Linux system doesn't get stuck when I dump small memory chunks giving a min max range of addresses. It only freezes when I get the dump of the whole 16 GB.
4) Some times while making these small memory dumps(I call it in a loop iterating over small chunks through a system() call using c programming) I get an error as follows in between :

"C:\cygnus\cygwin-b20\H-i586-cygwin32\bin\sh.exe: * unable to allocate heap, error 0
[main] C:\cygnus\cygwin-b20\H-i586-cygwin32\bin\sh.exe 4318 (0) sync_with_child: child 9460(0x144) died before initialization with status code 0x1
[main] sh 4318 (0) sync_with_child: * child state waiting for longjmp
Cannot fork"
5) As I told you before in the previous threads of this issue, that I used USB 3.0 and borrowed my friends system having SSD. With these things i was getting a dumping speed of 150MB/Sec but now I am.not getting that speed as well. With same apparatus : USB 3.0 + SSD now I am getting a speed of 25-35 MB/Sec.

Can you help me out with these issues and guide me what to do.

Thank you.

**Comment by meriniamjo** [comment]
By the way when I say my PCILEECH/dumping process got stuck, it means that the pcileech process/command ( ps aux | grep pcileech ) is in D state (sleep).

![dmesg_trace](https://cloud.githubusercontent.com/assets/15684232/20327539/7b24a792-ab5b-11e6-8a96-7210f0d05142.jpg)

After running the dmesg command I get this following result;

![dmesg_trace](https://cloud.githubusercontent.com/assets/15684232/20327519/605c0f2c-ab5b-11e6-9acc-b6b51a05f765.jpg)

**Comment by ufrisk** [comment]
Thanks for the stack trace. I need to look closer into it tomorrow to see if I see anything in it.

About the speed issue, have you verified that:

1) you do use an USB3-cable and not an ordinary USB2 cable?
2) you plugged in the USB3-cable in an USB3 port on your computer (blue usb connector)
3) that your HDD is capable of the data transfer speeds

(sorry for asking, but all these questions have solved the issues with regards to speed for various persons...)

**Comment by meriniamjo** [comment]
I think its the port issue. I have 2 ports in the laptop. One is USB 2.0 and one is USB 3.0. I was trying it in 2.0. So that might be the issue. 

 But its strange that I had got the high speed when I connected to usb 3.0 initially (few weeks back). But now the pcileech seems to not detect that port. It shows "Pcileech Failed to connect to USB". It works fine in the other usb 2.0 port.
And yes the laptop has SSD.

Leaving the speed issue out, my major concern is about the pcileech getting stuck in between taking dumps.
Hope it can be solved. (Sorry for the trouble)

**Comment by ufrisk** [comment]
I've had other users reporting pcileech getting stuck; the problem for that user went away when he replaced the USB2 cable he was using with a USB3 cable.

Due to this I'm a bit reluctant looking into the hangup issues as long as you run it over USB2. If you still get the same types of problems when running it over USB3 please let me know and I'll try my best looking into it.
