### ISSUE TITLE
Is there a signature file for windows 10 online account?

### ISSUE THREAD

**Issue by cofarmer** [ufrisk/pcileech#128]
Like the title, some body have ideas?

**Comment by ufrisk** [comment]
No, there is not, not right now at least.

I'll have some major updates on my way; that is still some time away. After that I'll have to check out this to see if I can come up with something.

Or if anyone else already have it?

**Comment by ufrisk** [comment]
Thanks for the update and the hints.

Ill have to look into this with these being more common.

But please keep in mind this is an open source project and the others that do the unlock have paid employees doing this on work hours.

Ill look into it once I finish a few other things I'm working on :)

**Comment by KrinalPatel889** [comment]
@ufrisk Any progress for online account?

**Comment by ufrisk** [comment]
Thanks for the reminder. I've actually forgot about this since last :(

In the near term I expect to be quite busy with real life and also with some sponsored development (new hardware and such). Hopefully I'll fix this in Q1 next year some time.

**Comment by KrinalPatel889** [comment]
I'll post reminder again after 3-4 months if I remember 😂

**Comment by KrinalPatel889** [comment]
@ufrisk
Would you be able to check MS live id signatures now?
or busy with work?

**Comment by KrinalPatel889** [comment]
@ufrisk.

**Comment by ufrisk** [comment]
Hi, I haven't looked into this yet.

**Comment by cofarmer** [comment]
already bypass online account with other way, thanks

**Comment by KrinalPatel889** [comment]
> already bypass online account with other way, thanks

Can you please share a method?

**Comment by LuckyPi** [comment]
@cofarmer 

I second @KrinalPatel889 's request for the method. If you use PCILeech as a bypass for unlocking a Windows host that uses Online "not local" authentication or other steps. Please share.

I myself usually just create an account, use the shell or push/execute a RAT. For me the unlock is great for demos and making it a lot easier to capture the users workspace for forensic purposes. It would be a nice feature for sure PCILeech already does a wonderful job at ganging access.

**Comment by ufrisk** [comment]
I've looked into this a bit, but my reversing skills aren't strong enough for me to quickly find out where to patch the lsass process to allow for a Microsoft account bypass. at least not in the time I put into it. I'll gladly implement something if someone can point me in the right direction.

Alternative methods would be to spawn a shell via kernel inject. If you wish to do that in the user context it's possible as well by specifying a PID.

Other methods would be to patch winlogon.exe to allow for the "sticky keys" to spawn a system shell. I haven't included it in PCILeech, but there is a signature here: https://github.com/signal-5/pcileech/blob/master/files/stickykeys_cmd_win.sig

**Comment by KrinalPatel889** [comment]
@cofarmer
Could you please comment on your online account bypass method?
