### ISSUE TITLE
USB3380-EVB and taget with M.2 slot?

### ISSUE THREAD

**Issue by jeroen-80** [ufrisk/pcileech#130]
What's the preferable way of connecting a USB3380-EVB to a M.2 slot? Can I just plug in the mini PCIE card (if physically possible)? Or use an adapter and if so, which ones are preferable? And what about the secondary slots you typically see in laptops (e.g. for WWAN/WLAN), will they work as well? Thanks!

**Comment by ufrisk** [comment]
It will not fit. Also M.2. slot is not a single form factor, it's multiple one. The most common being M.2 key A+E for (WLAN/WIFI) and M.2 key E for SSDs.

You'll have to check around for an adapter or a combination of two adapters, for example M.2 -> PCIe and PCIe -> miniPCIe.

**Comment by jeroen-80** [comment]
Thanks, clear!
