### ISSUE TITLE
M.2 Screamer Issue 

### ISSUE THREAD

**Issue by firehive101** [ufrisk/pcileech#132]
Hello,
I have recently bought an M.2 screamer board and I’m having massive issue when attempting to use PCILeech. I receive an 4,v4.3 meaning the usb connection from my screamer to my second PC is there but it isn’t connecting saying it has failed. 
I have tried using alternative USB 3-Micro B cable including the one provided by Lambda (the company I purchased the screamer off). Along with the alternative cables I have also attempted to change to a PCI-E X4 16 slot adapter with the exact same result.This was of course encountered after flashing stock software onto the device via a Jtag.
Someone assisting me in this matter noted that it could be certain settings in my BIOS causing this issue but I would appreciate any insight, I’m currently not in a position where I have a second pc available to test if the board itself is faulty.

Specs:
Motherboard: Gigabyte Z390 Ultra Durable 
CPU: I9 9900Ks

Would really appreciate any assistance in this as I’m not great at this aspect and don’t personally know anyone who can help me.

Cheers

**Comment by ufrisk** [comment]
what does it say after 4,v4,3 - is there a number or just four zeros?

**Comment by firehive101** [comment]
Thanks for the fast response, so it was four zeros after that error message but I also received a 4,v4,1 0000 message also.

**Comment by AcTiViSioN911** [comment]
I have [4,v4.3,0000] too

**Comment by firehive101** [comment]
So I assume your device also isn’t being read by the system?

**Comment by AcTiViSioN911** [comment]
In device manager i see "FTDI FT601 USB 3.0 Bridge Device" (VID_0403 PID_601F) and "USB Billboard device" (VID_2109 PID_8883), thats all. By command "pcileech.exe dump -out none -v -vv -device fpga" i get some results and then an error:
`----- FPGA DEVICE CONFIG REGISTERS: CORE-READ-ONLY     SIZE: 34 BYTES -----
0000    89 ab 00 00 22 00 00 00  04 03 04 00 00 00 00 00   ...."...........
0010    4b 24 df ac 0c 00 00 00  4d 24 df ac 0c 00 00 00   K$......M$......
0020    00 00                                              ..

----- FPGA DEVICE CONFIG REGISTERS: CORE-READ-WRITE    SIZE: 30 BYTES -----
0000    cd ef 04 00 1e 00 00 00  a0 86 01 00 00 00 00 00   ................
0010    ee 00 07 00 ee 00 66 06  02 1c 00 00 7f 00         ......f..... .

----- PCIe CORE Dynamic Reconfiguration Port (DRP)  SIZE: 0x100 BYTES -----
0000    00 00 00 01 00 02 00 00  00 00 00 00 00 00 f0 00   ................
0010    ff ff 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0020    00 00 00 00 00 00 00 00  00 00 00 40 00 00 00 00   ...........@....
0030    00 00 09 02 30 00 22 7f  02 00 01 00 00 03 11 0c   ....0." ........
0040    02 a1 00 43 01 00 1f fd  7f ff 09 ff 01 20 01 48   ...C.... .... .H
0050    00 05 01 60 11 9c 00 00  00 00 00 00 00 00 00 00   ...`............
0060    00 00 10 60 00 02 40 21  00 40 3d 48 00 23 00 00   ...`..@!.@=H.#..
0070    00 00 00 00 00 00 00 00  00 00 00 00 00 15 00 01   ................
0080    00 01 00 00 00 01 00 00  00 01 00 00 00 01 00 00   ................
0090    00 01 00 00 00 01 00 00  00 00 00 00 00 00 00 00   ................
00a0    00 00 00 00 00 00 00 00  00 02 00 00 12 34 10 18   .............4..
00b0    00 0b 00 01 00 11 00 00  00 00 00 00 00 01 00 00   ................
00c0    00 28 00 41 ff ff ff ff  00 e0 00 00 80 08 00 22   .(.A..........."
00d0    07 ff 03 52 02 48 00 08  00 40 0e 84 fa ac 00 00   ...R.H...@......
00e0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
00f0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................

DEVICE: FPGA: ERROR: Unable to retrieve required Device PCIe ID [4,v4.3,0000]
PCILEECH: Failed to connect to the device.`

**Comment by firehive101** [comment]
Mines also the same

**Comment by AcTiViSioN911** [comment]
ufrisk said that: The FTDI will show up on the PC when connected to the USB regardless of whether the device is flashed or not. If flashing with one of my more recent bitstreams (v4.3) you should see the the USB_DATA blink I think it's 3 times right after device power-on. Also you should be able to see a Xilinx Ethernet PCIe Device in Device Manager. If it's not blinking/showing up in device manager there was probably an issue with your flash and you would need to successfully re-flash.

**Comment by AcTiViSioN911** [comment]
I flashed his last firmware 4.3 but maybe im missing something...

**Comment by AcTiViSioN911** [comment]
I think we need a driver to see any name like "Xilinx Ethernet PCIe Device", how windows would know about that without any driver? I have windows ver. 2004 without auto-installation of drivers so my system just cant search for that in the internet, maybe you have the same problem?

**Comment by AcTiViSioN911** [comment]
But main idea of dma - no drivers, so...

**Comment by firehive101** [comment]
I’ve re-flashed with the stock firmware last night and still managed to receive the same issue is not sure if the flash is the issue due to still having two green lights present on the board.

**Comment by AcTiViSioN911** [comment]
I had first and third led green without blinking on stock firmware. After flashing his 4.3 i have third led green, first led blinking.

**Comment by firehive101** [comment]
I have solid green on first and third lights

**Comment by AcTiViSioN911** [comment]
Try [this firmware](https://mega.nz/#!ofogyYBS!lR3K6nMqS5PTqREXVC6uea_MQrjskwMs_alIxlGfXv8) and you will have same as me, it kind of works but i still get an error at the end.

**Comment by firehive101** [comment]
I’ll have a shot, I’m attempting to look in BIOS for any settings I have that could be causing issues with the code being read

**Comment by AcTiViSioN911** [comment]
Btw check this: https://github.com/ufrisk/pcileech-fpga/issues/46

**Comment by firehive101** [comment]
Thanks I’ll look into that too, it makes me feel better knowing two of us are having the same issue

**Comment by AcTiViSioN911** [comment]
Oh man, just remove any OC from ur pc, it works now! I think its RAM, ill try to OC it little by little.

**Comment by firehive101** [comment]
As in like CPU clock? Or purely ram

**Comment by AcTiViSioN911** [comment]
I removed both, CPU and RAM OC, but i think its all because of RAM speed, i had 4000mhz with CL17, i know its rly fast but i didnt think about that before.

**Comment by firehive101** [comment]
With the removing of the over clock have you managed to get the screamer to read?

**Comment by AcTiViSioN911** [comment]
yes, any command now works. but, i still dont see a Xilinx Ethernet PCIe Device... im not sure why, it works but i think i missed something...

**Comment by firehive101** [comment]
Is the screamer in the M.2 slot or the PCI-E?

**Comment by firehive101** [comment]
I’ve changed my RAM speed but don’t seem to see any difference

**Comment by AcTiViSioN911** [comment]
Screamer connected to "m.2 to pcie-x1 card", and this card in pcie-x1 slot.

**Comment by firehive101** [comment]
Interesting I’ll try that

**Comment by AcTiViSioN911** [comment]
It works on 2133, try that. Its 2 times slower than original 4000, so ill now try to change it.

**Comment by firehive101** [comment]
Brilliant, I’ll swap from the M.2 slot to the one you have then change my memory frequency to that

**Comment by AcTiViSioN911** [comment]
OCed my CPU to last settings and RAM to 3600 CL14, it works, lets try higher...

**Comment by AcTiViSioN911** [comment]
wtf... it works with 3866 CL14 and with 4000 CL15... i didnt test for stability. i dont remember what CL i had before, 15 or 17, but 15 is even faster anyway, and it works... maybe i just had to reoverclock my system?

**Comment by AcTiViSioN911** [comment]
> pcileech.exe probe
> 
>  Memory Map:
>  START              END               #PAGES
> 
> 
>  Current Action: Probing Memory
>  Access Mode:    Normal
>  Progress:       4096 / 4096 (100%)
>  Speed:          455 MB/s
>  Address:        0x0000000100000000
>  Pages read:     0 / 1048576 (0%)
>  Pages failed:   1048576 (100%)
> Memory Probe: Completed.

**Comment by AcTiViSioN911** [comment]
**Pages failed: 1048576 (100%)** hm....

**Comment by firehive101** [comment]
I've changed ports and everything im still getting read device failed, I don't know if the board itself is just faulty

**Comment by firehive101** [comment]
It’s so strange, in my BIOS all of my alternative PCIE ports are reading that there’s nothing plugged in

**Comment by ufrisk** [comment]
It may be a different issue. You may also try other pcie slots, try initialize the PCILeech/MemProcFS with extra option: `-device fpga://algo=2` (it's slow, but its reading this in a different way and it's known to work on some motherboards). Also you can try to have the board inserted when power on the computer and it may work (a reboot may be problematic in some cases though).

I'll try fix the known issues (especially with it being a bit unstable after reboot) next week. I also plan fixing the slowness but that may take a bit longer time.

**Comment by AcTiViSioN911** [comment]
What about 100% failed pages and only 4gb of ram except of 16?

**Comment by ufrisk** [comment]
If memory reads fail for some reason it will default to 4GB (which is what an older device - the usb3380 was capable of). That indicates its not working at all.

You may (after a fresh reboot) try:

`pcileech.exe display -min 0x1000 -max 0x2000 -v -device fpga://algo=2`

also, if it fails on first attempt try 1-2 more times. Also try to change slots, if you use an extension cord (such as of bitcoin mining adapter) try using it directly in a PCIe slot. Downclock RAM to default non OC. If this is not working it may also be related to some of the other issues I'm aware of, of which some I'll look into next week hopefully.

**Comment by firehive101** [comment]
I have a massive issue with the screamer not being able to be read in my BIOS, as in when looking at connected devices it shows nothing in any PCIE slot other than my graphics card

**Comment by AcTiViSioN911** [comment]
I fixed the problem ... in general, pcie x1 does not work, only pcie x4 needs to be used. The wire was very short and I used a USB extension cable. It seemed like it was my mistake. I have a mini-computer and I put it inside my main computer, right on the PSU. So I had enough wire to connect screamer (inserted into pcie x4) and a mini pc.

**Comment by firehive101** [comment]
So, I’ve tried all available ports tried all the wires I have I can’t get it to work

**Comment by AcTiViSioN911** [comment]
Did you flash it with 4.3 firmware? Use only included wire, or if you have fat 3.0 usb extender, i just found one short, but two together is ok, at least my pc isnt inside another. Check led lamps, i had 3 of them green, pushed reset button on screamer, now there is 1 and 3 leds green, but nothing changed unlit i turned pc off, waited 5 sec and turned on. Now it works. I think its a bug or something like that, it works and after i tried to overclock my pc it doesnt work anymore, even after removing any OC. I will try to OC my pc again, looking at led lamps and always completely off my pc.

**Comment by ufrisk** [comment]
Others have also reported problems with the v4.3 version of the bitstream in rare circumstances. You may also try version 4.1. But as mentioned, I'll try to be looking into these issues next week.

**Comment by AcTiViSioN911** [comment]
Rebooted PC 3 times, always checking, everything works.
OCed only CPU, booted PC, doesnt work.
Rebooted PC, checked, it works with OCed CPU.
Now ill try that with RAM...

**Comment by AcTiViSioN911** [comment]
firehive101 try to push reset button on screamer when your pc has no OC, and use only included shord usb 3.0 wire with pcie x4 card.

**Comment by firehive101** [comment]
I’ve found an issue, I have bent pins on my motherboard causing the slots to not function correctly. I’ve ordered a new motherboard in the hopes this will correct any issues. It will be here Monday I’ll leave the thread open and report progress

**Comment by firehive101** [comment]
I appreciate all of the help offered thankyou

**Comment by firehive101** [comment]
Just want to say anyone still observing this thread thankyou all for the fast responses and assistance. I have managed to get the screamer working it was an issue with my old motherboard, I’ve changed it out and get a reading now so thankyou again appreciate you all.

Cheers Josh

**Comment by imagerman999** [comment]
![IMG_1246](https://github.com/ufrisk/pcileech/assets/112811234/534eb7bd-6a82-4249-8c41-e5113b1807ba)
Could anyone help me with this Error ive tryed like every thing reboted the pc and stuf like that
