### ISSUE TITLE
Screamer M2 issue [0, v0.0,0000]

### ISSUE THREAD

**Issue by AcTiViSioN911** [ufrisk/pcileech#134]
Hello. I just can’t connect my Screamer M2. On command "pcileech.exe dump -out none -v -vv -device fpga" I get the error "DEVICE: FPGA: ERROR: Unable to retrieve required Device PCIe ID [0, v0.0,0000]
PCILEECH: Failed to connect to the device. "After 30 seconds. As I understand it, there is no connection via pcie and usb? But I successfully flashed it, so Screamer is working. I can see the FTDI FT601 USB 3.0 Bridge Device
 "USB \ VID_0403 & PID_601F" means there is a connection. And I see the USB Billboard Device "USB \ VID_2109 & PID_8883". I also see "IBtUsb_Filter_00" without any VId and Pid. I installed the FTD3XXDriver_WHQLCertified_v1.3.0.4 driver (tried 1.3.0.2 too, but if lower = an error about version). Without this driver, an error appears immediately, and not after 30 seconds. Any ideas what else can be done? I see only FPGA INIT green led. Before flashing i saw INIT and PCIE LINK leds.
![gh_m2_2 1](https://user-images.githubusercontent.com/10898099/86504706-f6fa7600-bd89-11ea-86c5-85e5652409cf.png)
sry for my english)

**Comment by ufrisk** [comment]
Yes, you would need the v1.3.0.4 driver; that is sorted out so it's not your issue.

The FTDI will show up on the PC when connected to the USB regardless of whether the device is flashed or not. If flashing with one of my more recent bitstreams (v4.3) you should see the the USB_DATA blink I think it's 3 times right after device power-on. Also  you should be able to see a Xilinx Ethernet PCIe Device in Device Manager. If it's not blinking/showing up in device manager there was probably an issue with your flash and you would need to successfully re-flash.

**Comment by AcTiViSioN911** [comment]
Ok but where can I get firmware for R03? I tried R02 from your 4.3 and my pcie led no more green, but on stock it was (but anyway it didn't work). Do you have a link for prebuilt file?
Also one time I saw xilinx device, I think on stock firmware, so now I will try to find correct one..

**Comment by AcTiViSioN911** [comment]
I found your latest 4.3 prebuilt firmware without R1 and R2 prefix, so flashed it, and now i have green FPGA INIT and blinking PCIE LINK.

**Comment by AcTiViSioN911** [comment]
One more question, i have i7 10700k on msi z490 gaming edge. Also i have two m.2 ssd in rain0, then one graphics card. Is there enought pcie lines?

**Comment by AcTiViSioN911** [comment]
Finally after reset button i was able to run this command:

pcileech.exe dump -out none -v -vv -device fpga


----- FPGA DEVICE CONFIG REGISTERS: CORE-READ-ONLY     SIZE: 34 BYTES -----
0000    89 ab 00 00 22 00 00 00  04 03 04 00 00 00 00 00   ...."...........
0010    60 a5 62 94 03 00 00 00  62 a5 62 94 03 00 00 00   `.b.....b.b.....
0020    00 00                                              ..

----- FPGA DEVICE CONFIG REGISTERS: CORE-READ-WRITE    SIZE: 30 BYTES -----
0000    cd ef 04 00 1e 00 00 00  a0 86 01 00 00 00 00 00   ................
0010    ee 00 07 00 ee 00 66 06  02 1c 00 00 7f 00         ......f..... .

----- PCIe CORE Dynamic Reconfiguration Port (DRP)  SIZE: 0x100 BYTES -----
0000    00 00 00 01 00 02 00 00  00 00 00 00 00 00 f0 00   ................
0010    ff ff 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0020    00 00 00 00 00 00 00 00  00 00 00 40 00 00 00 00   ...........@....
0030    00 00 09 02 30 00 22 7f  02 00 01 00 00 03 11 0c   ....0." ........
0040    02 a1 00 43 01 00 1f fd  7f ff 09 ff 01 20 01 48   ...C.... .... .H
0050    00 05 01 60 11 9c 00 00  00 00 00 00 00 00 00 00   ...`............
0060    00 00 10 60 00 02 40 21  00 40 3d 48 00 23 00 00   ...`..@!.@=H.#..
0070    00 00 00 00 00 00 00 00  00 00 00 00 00 15 00 01   ................
0080    00 01 00 00 00 01 00 00  00 01 00 00 00 01 00 00   ................
0090    00 01 00 00 00 01 00 00  00 00 00 00 00 00 00 00   ................
00a0    00 00 00 00 00 00 00 00  00 02 00 00 12 34 10 18   .............4..
00b0    00 0b 00 01 00 11 00 00  00 00 00 00 00 01 00 00   ................
00c0    00 28 00 41 ff ff ff ff  00 e0 00 00 80 08 00 22   .(.A..........."
00d0    07 ff 03 52 02 48 00 08  00 40 0e 84 fa ac 00 00   ...R.H...@......
00e0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
00f0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................

DEVICE: FPGA: ERROR: Unable to retrieve required Device PCIe ID [4,v4.3,0000]
PCILEECH: Failed to connect to the device.

But now another error, 0000, what can i do?

**Comment by ufrisk** [comment]
I'm closing this issue since it seems it was resolved in the other thread.
