### ISSUE TITLE
Unable recognize beyond 4gb of ram - 10900K + z490 Mobo + 32gb RAM

### ISSUE THREAD

**Issue by Adealia** [ufrisk/pcileech#136]
Hello,

Been having a challenge with running PCILeech on a newer system. Attempting to verify connection with:

`pcileech.exe device fpga://algo=2 -vv`

It appears to be only recognizing the first 4gb and only 22% of that is a success.
```
 Current Action: Probing Memory
 Access Mode:    Normal
 Progress:       4096 / 4096 (100%)
 Speed:          409 MB/s
 Address:        0x0000000100000000
 Pages read:     237280 / 1048576 (22%)
 Pages failed:   811296 (77%)
Memory Probe: Completed.
```

My system specs are as follows:

**CPU**: Intel i9-10900k
**Motherboard**: Gigabyte Aorus Master
**RAM**: 32gb 2133MHz (XMP up to 4400MHz)
**Windows Version**: Ver 2004 (19041.329)
**XMP**: Disabled
**VT-d**: Disabled
**Secure Boot**: Disabled

Any suggested solutions or indication to what I'm overlooking would be much appreciated

**Comment by ufrisk** [comment]
can you please retry this with v4.4 of the fpga bistream recently released at https://github.com/ufrisk/pcileech-fpga to see if this resolves your issue?

**Comment by ufrisk** [comment]
I'm closing the issue since I assume it's resolved (no answer for a month). Please let me know and re-open the issue if it should still persist even with the new pcileech release.
