### ISSUE TITLE
Unable to retrieve required Device PCIe ID

### ISSUE THREAD

**Issue by vinnyNC** [ufrisk/pcileech#137]
> C:\Users\Vincent\Downloads\Screamer\DMAStuff\MemProc>MemProcFS.exe -v -vv -device fpga
> 
> ----- FPGA DEVICE CONFIG REGISTERS: CORE-READ-ONLY     SIZE: 34 BYTES -----
> 0000    89 ab 00 00 22 00 00 00  04 03 04 00 00 00 00 00   ...."...........
> 0010    a4 2c a0 d8 01 00 00 00  a6 2c a0 d8 01 00 00 00   .,.......,......
> 0020    00 00                                              ..
> 
> ----- FPGA DEVICE CONFIG REGISTERS: CORE-READ-WRITE    SIZE: 30 BYTES -----
> 0000    cd ef 04 00 1e 00 00 00  a0 86 01 00 00 00 00 00   ................
> 0010    ee 00 07 00 ee 10 66 06  02 3c 00 00 7f 00         ......f..<.. .
> 
> ----- FPGA DEVICE CONFIG REGISTERS: PCIE-READ-ONLY     SIZE: 48 BYTES -----
> 0000    01 23 00 00 30 00 00 00  00 00 19 08 7c 00 00 00   .#..0.......|...
> 0010    00 00 00 00 00 00 00 02  10 29 00 00 00 00 00 00   .........)......
> 0020    12 10 00 00 1e 7f 00 00  00 00 ff f9 00 00 00 00   ..... ..........
> 
> ----- FPGA DEVICE CONFIG REGISTERS: PCIE-READ-WRITE    SIZE: 84 BYTES -----
> 0000    45 67 00 f0 54 00 00 00  35 0a 00 01 01 00 00 00   Eg..T...5.......
> 0010    00 00 00 00 ff fd 48 00  00 00 00 0e 00 00 00 00   ......H.........
> 0020    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
> 0030    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
> 0040    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
> 0050    00 00 00 00                                        ....
> 
> ----- PCIe CORE Dynamic Reconfiguration Port (DRP)  SIZE: 0x100 BYTES -----
> 0000    00 00 00 01 00 02 00 00  00 00 00 00 00 00 f0 00   ................
> 0010    ff ff 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
> 0020    00 00 00 00 00 00 00 00  00 00 00 40 00 00 00 00   ...........@....
> 0030    00 00 09 02 30 00 22 7f  02 00 01 00 00 03 11 0c   ....0." ........
> 0040    02 a1 00 43 01 00 1f fd  7f ff 09 ff 01 20 01 48   ...C.... .... .H
> 0050    00 05 01 60 11 9c 00 00  00 00 00 00 00 00 00 00   ...`............
> 0060    00 00 10 60 00 02 40 21  00 40 3d 48 00 23 00 00   ...`..@!.@=H.#..
> 0070    00 00 00 00 00 00 00 00  00 00 00 00 00 15 00 01   ................
> 0080    00 01 00 00 00 01 00 00  00 01 00 00 00 01 00 00   ................
> 0090    00 01 00 00 00 01 00 00  00 00 00 00 00 00 00 00   ................
> 00a0    00 00 00 00 00 00 00 00  00 02 00 00 12 34 10 18   .............4..
> 00b0    00 0b 00 01 00 11 00 00  00 00 00 00 00 01 00 00   ................
> 00c0    00 28 00 41 ff ff ff ff  00 e0 00 00 80 08 00 22   .(.A..........."
> 00d0    07 ff 03 52 02 48 00 08  00 40 0e 84 fa ac 00 00   ...R.H...@......
> 00e0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
> 00f0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
> 
> ----- PCIe CONFIGURATION SPACE (no user set values) SIZE: 0x200 BYTES -----
> 0000    00 00 00 00 00 00 10 00  02 00 00 02 00 00 00 00   ................
> 0010    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
> 0020    00 00 00 00 00 00 00 00  00 00 00 00 ee 10 07 00   ................
> 0030    00 00 00 00 40 00 00 00  00 00 00 00 ff 01 00 00   ....@...........
> 0040    01 48 03 78 08 00 00 00  05 60 80 00 00 00 00 00   .H.x.....`......
> 0050    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
> 0060    10 00 02 00 e2 8f 00 00  10 29 00 00 12 f4 03 00   .........)......
> 0070    00 00 12 10 00 00 00 00  00 00 00 00 00 00 00 00   ................
> 0080    00 00 00 00 02 00 00 00  00 00 00 00 00 00 00 00   ................
> 0090    02 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
> 00a0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
> 00b0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
> 00c0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
> 00d0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
> 00e0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
> 00f0    00 00 00 00 00 00 00 00  00 00 00 00 03 00 c1 10   ................
> 0100    00 00 00 00 35 0a 00 01  01 00 00 00 00 00 00 00   ....5...........
> 0110    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
> 0120    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
> 0130    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
> 0140    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
> 0150    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
> 0160    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
> 0170    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
> 0180    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
> 0190    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
> 01a0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
> 01b0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
> 01c0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
> 01d0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
> 01e0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
> 01f0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
> 
> DEVICE: FPGA: ERROR: Unable to retrieve required Device PCIe ID [4,v4.3,0000]
> MemProcFS: Failed to connect to memory acquisition device.

Using Screamer M2 (R03).
Target PC Specs:
i9-10940x
ASUS ROG Extreme Omega

I can't figure out what is wrong. I've tried stock default firmware and custom. Same message. I get 2 green LEDs constant and the middle one flashes 4 times on boot.

**Comment by ufrisk** [comment]
I'll be issuing a fix later this week, maybe tomorrow, that may or may not fix your specific issue. Lets await that and see if the issue resolves.

Once you re-flashed please let me know here if the issue is resolved or not.

**Comment by vinnyNC** [comment]
Just wanted to leave update. I flashed with 4.6 and had to connect via M2 slot for it to work. We are up and running now, appreciate it.
