### ISSUE TITLE
Help in understanding Pcileech

### ISSUE THREAD

**Issue by uranusb** [ufrisk/pcileech#138]
Hello again,

Thanks for helping me previously. Now that I have seen the attack in action, I want to learn the detail of DMA attack. Would you recommand me some source to read about PCIE connection with DMA and the packets transferred between these devices to perform the setup? 

Any help will be greatly appreciated.

**Comment by ufrisk** [comment]
http://xillybus.com/tutorials/pci-express-tlp-pcie-primer-tutorial-guide-1

PCI Express Base Specification - https://pcisig.com/specifications/pciexpress/technical_library/pciexpress_whitepaper.pdf

**Comment by uranusb** [comment]
Thanks!

I will read these documentations, and let you know if I get any new issues.

**Comment by ufrisk** [comment]
Awesome and if you have any more general questions I'll try to be around both on twitter and on discord in #pcileech channel.
