### ISSUE TITLE
kmdload/vmm.dll - Win10

### ISSUE THREAD

**Issue by yoranjj** [ufrisk/pcileech#144]
Hello! This issue might be related to #112.

Victim/target: Win 10 x64 (build 19041), Ryzen 3900x, x570 Aorus Ultra

**./pcileech.exe kmdload -kmd win10_x64_2 -device fpga -v -vv**

> MemProcFS: Failed to initialize memory process file system in call to vmm.dll!VMMDLL_Initialize
> KMD: Failed initializing required MemProcFS/vmm.dll
> PCILEECH: Failed to load kernel module.

Probing/dumping/displaying works perfectly fine but kmdload doesn't. Screamer M2 R04 is currently flashed v4.6, PCILeech 4.4 along side the 1.3.0.4 FTD3XX.dll binary from ftdichip.com. Virtualization and IOMMU are both currently disabled on the target machine.

![55843f2df10d24806620d8d24f0d6984dfe74bd7aa0bb985](https://user-images.githubusercontent.com/17703007/88295777-29025680-ccfe-11ea-81e3-d9e545785fae.png)

--

Running the example you gave in a pcileech-fpga issue https://github.com/ufrisk/pcileech-fpga/issues/33#issuecomment-510574953 resulted in me getting the error below;

VmmWinInit_TryInitialize: Initialization Failed. Unable to locate ntoskrnl.exe.

![16b8cd15badbda42798b0c0df9c4af8edf9a4c4964c187e4](https://user-images.githubusercontent.com/17703007/88296491-0cb2e980-ccff-11ea-8744-46f073e08788.png)

**Comment by ufrisk** [comment]
Ryzen is not supported by the PCILeech on the software side right now.

I plan to release the fixes in a few weeks time.

**Comment by ufrisk** [comment]
I just released support for AMD Ryzen.

Since this should now be fixed I'm closing the issue. If you should still experience any issues please let me know and re-open the issue.
