### ISSUE TITLE
Can anyone part ways with a device usable with pci-e leech

### ISSUE THREAD

**Issue by nicholaskunes** [ufrisk/pcileech#147]
Preferably an old screamer or other artix 7 fpgas, retail costs are insane, willing to buy used but working.

**Comment by ufrisk** [comment]
Closing issue. The issue section is not a buy/sell board; I put a separate thread for this a long time ago though.

Also my project is free and open source. I get absolutely nothing back from those device sales even tho they are just to run my software.

And don't buy one of the older pciescreamers; they lack hatdware support for some stability improvment features. Get the M2 or one of the other supported devices instead.
