### ISSUE TITLE
kmd for windowsx86

### ISSUE THREAD

**Issue by cyttek** [ufrisk/pcileech#148]
i have try the Commands dump, write,search, display in x86 Windows 7 and works fine, but there is no kernel module and options available for Windows x86 what else do you recommend for fast mounting or get a cmd or other fast uses that you have for x64.

And why there is no kmd for x86?

regards

**Comment by ufrisk** [comment]
I'm closing this issue due to old age.

I won't add x86 support to the open source variant of PCILeech due to the work involved (and no real gain for me).

If there is a need for this I could do a sponsored development.
