### ISSUE TITLE
Built-in signatures for Win10x64 10.0.119041, version 2004.

### ISSUE THREAD

**Issue by LuckyPi** [ufrisk/pcileech#151]
Hey Ulf, I can confirm that the built-in signatures `-kmd WIN10_X64` or `-kmd WIN10_X64_2` aren't working against Windows 10 x64 10.0.119041, version 2004. Tested on two separate systems. MemProcFS is working great! 

Tested using the PCILeech_files_and_binaries_v4.6-20200830.zip release.

Any thoughts?    
```
>pcileech.exe kmdload -kmd WIN10_X64 -v

KMD: Failed. Failed finding entry point.
PCILEECH: Failed to load kernel module.
```
```
>pcileech.exe kmdload -kmd WIN10_X64_2 -memmap auto -v

TARGET SYSTEM MEMORY MAP:
   #       RANGE_BASE          RANGE_TOP         RANGE_REMAP
============================================================
0000             1000 -            9efff ->             1000
0001           100000 -         8d36efff ->           100000
0002         8f40e000 -         8f40efff ->         8f40e000
0003        100000000 -        86dffffff ->        100000000

KMD: Failed locating function hook pointer.
PCILEECH: Failed to load kernel module.
```

**Comment by ufrisk** [comment]
Thank You; this is a combination of issues it seems like. 1st one is an overly stririgent check in MemProcFS vmm.dll (which I use for the WIN10_X64_2 signature). This one will be super easy to fix. I could push a new build tomorrow already with a bit of luck.

2nd issue is that Windows have changed default memory allocation to be read-write memory (and not read-write-execute) which will cause blue screens currently. I would need to look into this more to see what I can do. If I'm lucky I could get away with a minor modification; if unlucky I probably have to rewrite quite a lot of things. This is likely to take some more time; maybe I'll be able to look into this in the weekend.

Thanks for reporting :)

**Comment by LuckyPi** [comment]
Thanks for looking into it! I also noticed the blue screens in my testing.

**Comment by ufrisk** [comment]
Thanks, I now see I messed up the kernel inject in the last update ( WIN10_X64_2 ). I'll release a new version and fix this later this week. Regardless of this it may cause blue screens. For the bluescreens to disappear I need to redo how I do things which will take some time and it's not an immediate priority as-is right now. But expect a fix later this week.

**Comment by LuckyPi** [comment]
No rush on my part, I figured MS was making it more difficult with v2004. Thanks for looking into it!

**Comment by ufrisk** [comment]
I fixed this by releasing a new kernel inject - `WIN10_X64_3`

It's super stable across all win10 versions from what I've seen. The other KMDs have a chance of bluescreening; I have yet to see a bluescreen with this one even tho my testing is somewhat limited.

Can you test and possibly update your tool? I would think you could either add it, or just replace the old WIN10_X64_2 with this one since it seems to be working better in all situations anyway.

Can you please confirm it's working on Win10 2004 release?

**Comment by LuckyPi** [comment]
Ulf, great! I'll check it out.  Perhaps I should remove the other Win10
KMDs and just use this one and the Win7 injects?

**Comment by ufrisk** [comment]
I would think that the original WIN10_X64 signature would make sense in some situations (when the WIN10_X64_3 signature for some reason fails to locate the targeted injection points). The original signature does things in a different way so mbe keep that one as a secondary option if the new one does not work. The WIN10_X64_2 would make less sense to keep though.

**Comment by LuckyPi** [comment]
Ulf, WIN10_X64_3 seems very stable! I updated to reflect the new signature. Thanks! https://github.com/LuckyPi/PushPin/releases/tag/V1.1

**Comment by ufrisk** [comment]
awesome, I'll tweet about it :) huge thanks!

system shell is not working on Windows 10 20.04 though.

user shell, file system and the other functionality is. Will post an issue shortly.

**Comment by ufrisk** [comment]
I'm closing this issue since it's now resolved. Huge thanks for reporting and thank you for the awesome frontend :)

**Comment by LuckyPi** [comment]
> I'm closing this issue since it's now resolved. Huge thanks for reporting and thank you for the awesome frontend :)

Awesome! Glad its working for you. Thank you!
