### ISSUE TITLE
ScreamerM2(R04) FAILED in GET DEVICEID

### ISSUE THREAD

**Issue by 0bing0** [ufrisk/pcileech#154]
Hi,

I am doing a ScreamerM2(R04) FPGA board test. I think the board isconfigured correctly. Here is the command I test. "pcileech.exe -device FPGA://pciegen=2 testmemread -v -vv -min 0x1000". The test failed with the error info "DEVICE: FPGA: ERROR: Unable to retrieve required Device PCIe ID [4,v4.7,0000]; PCILEECH: Failed to connect to the device." Detail info is as follow.
![Capture1](https://user-images.githubusercontent.com/73578925/98618776-d5635980-233c-11eb-956f-56da92288b1f.JPG)

I take a deep look into the source and the error is:
PROJECT LeechCore ==> FILE device_fpga.c ==> FUNCTION DeviceFPGA_GetDeviceID_FpgaVersionV4() ==> CODE DeviceFPGA_ConfigRead(ctx, 0x0008, (PBYTE)&wbsDeviceId, 2, FPGA_CONFIG_PCIE | FPGA_CONFIG_SPACE_READONLY); ==> CODE status = ctx->dev.pfnFT_ReadPipe(ctx->dev.hFTDI, 0x82, pbRxTx, 0x20000, &cbRxTx, NULL);
I get deviceid value is 0, which indicates an error. Here is the debug info.
![Capture2](https://user-images.githubusercontent.com/73578925/98619491-4eaf7c00-233e-11eb-9211-05a9f17eb2c7.JPG)

Do you have some advices that I can do to continue my test?

PS, my environment:
ScreamerM2(R04) gateways: Ver 4.5 and 4.6 and 4.7
PCILeech: Ver 4.7 and MASTER

**Comment by ufrisk** [comment]
apologies for the late answer; I kinda missed this one. Did you mange to resolve the issue?

You have an issue with your PCIe connection to the target PC; the PCIe core of the fpga haven't been assigned a device id by the host system. power on your target system (from off state) sometime solve it; somtimes changing slot also work. if you use an extension cord or something like that try to avoid it if having issues since it degrades signal quality and may result in the device not being detected.

**Comment by 0bing0** [comment]
Thanks a lot. It seems that something is wrong with my M2 slot on my laptop. I do a test on PCIE board on desktop PC, and it works well.

**Comment by 0bing0** [comment]
Hi, 

Since that some laptops only have Thunderbolt3, and may not have a PCIe or M.2, Do you think that ScreamerM2 can work normally on such "Thunderbolt3 to M.2 SSD devices"?
 EG. https://www.amazon.co.uk/Certified-Thunderbolt-Enclosure-WAVLINK-Excluding/dp/B0823X93SS
 (or many others can be found from Amazon. https://www.amazon.co.uk/s?k=Thunderbolt+3+To+NVME+M.2&i=computers&qid=1606965929&ref=sr_pg_1)

Or, have you studied before that there is a Thunderbolt 3 switching device that works properly with ScreamerM2?

**Comment by ufrisk** [comment]
I can't promise that the device will work; but it absolutely seems to be promising and would be a convenient way to access PCIe on your laptop.

However; thunderbolt is likely to be fairly well secured by default so chances are you need to disable some Thunderbolt security settings in the UEFI/BIOS settings and such before being able to use it.

**Comment by ufrisk** [comment]
I hope you managed to get it working and that you found the right adapters :) Since I haven't heard back for a while I'm assuming that's the case. I'll be closing this issue now.
