### ISSUE TITLE
Device ID (UUID) PP3380-AB

### ISSUE THREAD

**Issue by buecheko** [ufrisk/pcileech#155]
Hi, 

is it possible to alter the PCI device ID on a PP3380-AB Device like on the ScreamerM2?
Am I right, that the device ID is the same as the UUID found by the tbtadm Tool on Linux when using a the PP3380-AB over Thunderbolt?

**Comment by ufrisk** [comment]
Yes; it's possible to change the PCIe Device ID. You would need to change the values here: https://github.com/ufrisk/pcileech/blob/f72cc743691bbca42b19b17e6191bad11e0b8e28/usb3380_flash/linux/pcileech_flash.c#L47 and reflash.

My DEF CON talk have some info what the values mean on the firmware slide: https://github.com/ufrisk/presentations/blob/master/DEFCON-24-Ulf-Frisk-Direct-Memory-Attack-the-Kernel-Final.pdf

I don't think the TB3 UUID is the same as the PCIe Device ID; but please check it out.

**Comment by buecheko** [comment]
Thanks for your reply. 
You were right, the Thunderbolt UUID does not change with the Device ID. 
I am using a Sonet Echo Expresscard/34 TB  Adapter which sets the Thunderbolt UUID.
