### ISSUE TITLE
USB not enumerating

### ISSUE THREAD

**Issue by blackhawkswin** [ufrisk/pcileech#16]
Like user iTestAndroid in issue #14 I had an issue flashing my PP3380 using Ubuntu 16.04.1 LTS kernel 4.4.0-62-generic. I ended up using the PLX SDK to flash the device with firmware_pcileech.bin.

The issue I originally encountered was the same PCILEECH FLASH: ERROR: Firmware write/verify not successful error. I had not been able to resolve this issue, so I used the PLX SDK.

After flashing the, the output from PlxCm eep command gives the following:

```
>eep

   ------ 8505 EEPROM Header ------
 Signature    : 5A [Valid]
 Registers    : 42 bytes (7 regs)

   #    Port     Offset     Value
 -----------------------------------
   0     04       008C     00003849
   1     00       0000     16BC14E4
   2     04       0320     00040602
   3     04       0340     00040684
   4     04       0360     00040686
   5     04       0380     00040688
   6     04       0084     900118D1
```

Which corresponds directly with firmware_pcileech.bin.

However, when I plug the USB port into my windows machine it never enumerates, and installation of the Android USB driver (Android ADB interface) gives the following: This device cannot start (Code 10). I assumed this was because I installed the driver prior to connecting the device. However, after connecting the device, it doesn't appear to enumerate. I confirmed by deleting the driver then connecting the device. I assume, probably incorrectly, that the device should show up as an Other, but I don't see anything.

Suggestions? Recommendations?

**Comment by ufrisk** [comment]
Quick question: do you still have the J3 jumper bridged? The jumper must always be bridged.

**Comment by blackhawkswin** [comment]
Yes.

**Comment by ufrisk** [comment]
And your windows box doesn't detect any new USB device whatsoever when you connect the PCILeech device? Not even an unknown device?

If that's the case the most probable reason is that something went wrong in the flashing process. The USB port is disabled by default, and the device must be flashed in order to enable it. 

Are you able to re-check that flashing went ok?. Also PlxEep might work better than PlxCm for the PP3380.

**Comment by blackhawkswin** [comment]
Turns out it was failed flashing. I pulled the EEPROM off the board and read it with a programmer. It was still blank which doesn't explain the output from PlxCM. Anyway, I used the programmer to program firmware_pcileech.bin and everything works. Interestingly, I couldn't get PlxEep to take a 2 byte address width. It always failed indicating it couldn't set the width. 

Still wonder why the linux kernel module didn't work. I'll look into it. I suspect it may have to do with setting the address width, EepAddrWidth. I added some debug code to the kernel module, and I can see that EepAddrWidth is set to undefined (00). This makes sense considering the flash was blank, and the chip couldn't identify the signature byte 0x5A. I suspect now that it's flashed it will work, but since I want to play around first, I'll wait to give it a try.

When I get time, I'll poke around to see if I can't find a root cause, and identify a solution.

Thanks.

**Comment by ufrisk** [comment]
Awesome =)

If you have time please look into the kernel module. More ppl had problems flashing using it, especially the PP3380. Interestingly enough I never had a problem with it.

And yes, I know that the PLX tools doesn't exactly offer top notch stability and reliability.
