### ISSUE TITLE
VMMDLL_ProcessMap_GetModuleFromName could not be located in dynamic link library

### ISSUE THREAD

**Issue by SubCookie** [ufrisk/pcileech#160]
I am getting the following error:
>  The procedure entry point VMMDLL_ProcessMap_GetModuleFromName could not be located in the dynamic link library
![leech_test_aj1TYMW8kN](https://user-images.githubusercontent.com/23148833/106505195-3f1c7b00-64c8-11eb-9627-d3b585f18c3d.png)

I downloaded the most recent release from Github

**Comment by ufrisk** [comment]
Thanks. I renamed those functions very recently and I must have forgotten to update PCILeech whilst including the new library in the download. I'll fix it ASAP and let you know once it's resolved. Apologies for the inconvenience and huge thanks for letting me know about it.

**Comment by SubCookie** [comment]
thank you for replying so quickly!

**Comment by SubCookie** [comment]
it was on my end, accidentally used the wrong version that I still had on my PC. 

my excuses.

**Comment by ufrisk** [comment]
I looked more into this; you must be using an older version of PCIleech (i.e. not the most recent binary) with a new vmm.dll from the latest MemProcFS release.

I though I missed something in the very latest release; which is not the case it seems like. Older versions with PCILeech will be incompatible sometimes with newer released of MemProcFS; but if they are packaged together they should work :)

Anyway, closing this issue.  And Good Luck with everything 👍
