### ISSUE TITLE
I am a novice, how to read memory?

### ISSUE THREAD

**Issue by bbhxwl** [ufrisk/pcileech#166]
I am a novice, how to read memory?
I bought DMA and used a pubg DC radar, which can be used normally. It seems that it detects the svchost process. I want to read the memory myself. How can I get started?

**Comment by ryzen7i7** [comment]
I will answer this.
Basically https://github.com/ufrisk/LeechCore is API for PCILeech gateway.
You need to fluent with "C/C++, Python, C#" which are supported by LeechCore API.
And maybe, There is LeechCore compatible lib for Rust.
There is a LeechCore wiki:
https://github.com/ufrisk/LeechCore/wiki


Also, I don't think this project is meant to encourage illegal activity as cheatings.
Someone(or Me) can teach you how to read and write memory with LeechCore, but no one can give you a cheat tutotorial.

If you do not know basic programming knowledge:
https://www.learn-c.org/
https://www.learnpython.org/

**Comment by bbhxwl** [comment]
> I will answer this.
> Basically https://github.com/ufrisk/LeechCore is API for PCILeech gateway.
> You need to fluent with "C/C++, Python, C#" which are supported by LeechCore API.
> And maybe, There is LeechCore compatible lib for Rust.
> There is a LeechCore wiki:
> https://github.com/ufrisk/LeechCore/wiki
> 
> Also, I don't think this project is meant to encourage illegal activity as cheatings.
> Someone(or Me) can teach you how to read and write memory with LeechCore, but no one can give you a cheat tutotorial.
> 
> If you do not know basic programming knowledge:
> https://www.learn-c.org/
> https://www.learnpython.org/

I am proficient in C # language, programming is no problem, I do not know the specific method of operation, I just want to know I said the software, how to call the library

I want to know how to read a process, such as the memory of a certain 0x000086 in a.exe.

**Comment by ryzen7i7** [comment]
I don't speak any language except C/Rust for personal reasons, So I'm sorry for all the links, but there is might be great sample:
https://github.com/ufrisk/MemProcFS/tree/master/vmmsharp

**Comment by bbhxwl** [comment]
> I don't speak any language except C/Rust for personal reasons, So I'm sorry for all is just linking, but there is might be great sample:
> https://github.com/ufrisk/MemProcFS/tree/master/vmmsharp

I want to use the CMD command to read the memory first, and install DMA on the computer without installing any software, right? Do you need to install software on the computer connected by USB in DMA to read the memory?

**Comment by ryzen7i7** [comment]
If you use a DMA-FPGA Device, you don't have to touch the disk space of victim computer.
You need to create a connector(LeechCore) to the DMA Device on the attacker computer.

**Comment by ryzen7i7** [comment]
I have not checked if this is possible in C# API, but I rpm this way in C, 
VMMDLL_MemRead(DWORD dwPID, ULONG64 qwA, PBYTE pb, DWORD cb)

It works basically similar way as WINAPI.

**Comment by ryzen7i7** [comment]
If the problems has been solved or you no longer need to questions about it, I suggest that you close the issue.

**Comment by ufrisk** [comment]
I'm closing this issue since it seems to be resolved. Also I'd prefer that cheat related things be discussed elsewhere.

With that being said the MemProcFS library is the way to go. I have APIs for C# as previously mentioned and the example should hopefully be pretty straightforward. Also, if you should run into anything in the future, wish for features and such please let me know. Try to keep it general though and not mention games and such.

Good Luck and best wishes with your memory analysis.

**Comment by bbhxwl** [comment]
I don't know what program to install on my computer to read memory through DMA. I am Chinese, English may not be good, the use of translation software.

**Comment by bbhxwl** [comment]
> If the problems has been solved or you no longer need to questions about it, I suggest that you close the issue.
I am a beginner, DMA has been confirmed installed, computer a motherboard installed DMA, and then USB connection to computer B, I should install in computer B what software, can read memory?

**Comment by atao168** [comment]
QQ？多少？

**Comment by bbhxwl** [comment]
> QQ？多少？

啥事大兄弟，你q多少，学什么语言的

**Comment by atao168** [comment]
3539361562




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ufrisk/pcileech"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月7日(星期天) 中午12:04
收件人:&nbsp;"ufrisk/pcileech"<pcileech@noreply.github.com&gt;;
抄送:&nbsp;"归依我佛"<3539361562@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ufrisk/pcileech] I am a novice, how to read memory? (#166)





  
QQ？多少？
  
啥事大兄弟，你q多少，学什么语言的

**Comment by ryzen7i7** [comment]
> I don't know what program to install on my computer to read memory through DMA. I am Chinese, English may not be good, the use of translation software.

I have already answered your questions.
You should use LeechCore library to create your program.

No offence, But if you don't understand what the API means, you should start leaning again with simple Windows programming.
You need to place the FTD3XX Driver same directory to your dma program. It's needed to make the connection with DMA board via USB.

Also, with deepl.com you should be able to translate naturally between various languages and Chinese.

**Comment by bbhxwl** [comment]
> > I don't know what program to install on my computer to read memory through DMA. I am Chinese, English may not be good, the use of translation software.
> 
> I have already answered your questions.
> You should use LeechCore library to create your program.
> 
> No offence, But if you don't understand what the API means, you should start leaning again with simple Windows programming.
> You need to place the FTD3XX Driver same directory to your dma program. It's needed to make the connection with DMA board via USB.
> 
> Also, with deepl.com you should be able to translate naturally between various languages and Chinese.

I see. Where can I download the ftd3xx driver? I know how to read the memory. I need to read the process ID and then read the memory. I read the API document and it seems that I can enter the memory address directly without the process ID?

**Comment by ryzen7i7** [comment]
https://ftdichip.com/drivers/d3xx-drivers/
Just google everything please.

Also, "VMMDLL_PidGetFromName" can be used to find the pid from process name.
then get process module with "VMMDLL_ProcessMap_GetModuleFromName".
And it is a pain to find a process by directly set that's base address.

**Comment by wxjrkm520** [comment]
> QQ？多少？

丢大脸了兄弟
