### ISSUE TITLE
Please help, Can't find 'vfs_read' function for 'kmd LINUX_X64_48'

### ISSUE THREAD

**Issue by diablo0822** [ufrisk/pcileech#170]
While i try this pcileech target an x86_64 Linux base on CentOS. with the kernel version 4.18.0.
this command "pcileech.exe kmdload -kmd LINUX_X64_48" return error.
By some debugs,  i find it failed whie looking up the functions 'vfs_read' in kernel:

in funtion 'KMD_Linux48KernelSeekSignature':
`KERNELSEEKER ks[3] = {
        { .pbSeek = (PBYTE)"\0kallsyms_lookup_name",.cbSeek = 22 },
        { .pbSeek = (PBYTE)"\0vfs_read",.cbSeek = 10 },
        { .pbSeek = (PBYTE)"\0kdbgetsymval",.cbSeek = 14 }
    };`

'DeviceReadDMA(paKernelBase, KMD_LINUX48SEEK_MAX_BYTES, pb, pPageStat);'
i searched the function names in the buff 'pb', i can find ‘kallsyms_lookup_name’ and 'kdbgetsymval', but no 'vfs_read'. But i can find 'vfs_read' in /proc/kallsyms.  i don't konw why this happened.
And i tried to expand the buffer size from 32M to 128M, but i still get the same error. 
`#define KMD_LINUX48SEEK_MAX_BYTES       (0x02000000*4)      // 32MB`

Can i change the funtion 'vfs_read' to 'vfs_link' ? Cause i can find this function in 'pb'.

**Comment by ufrisk** [comment]
Hi,

Exported functions are constantly changing in Linux and also between distros. It's very hard for me to keep track of all this so I try to support 64-bit Ubuntu at the very least.

The vfs_read function is used to hook into execution flow; you could try to replace it with another function to see if it works.

It may also be another issue that would require me to dig a bit deeper into this; but first let's try to see if changing the hook function will work. Best here would be to hook an exported function which is called fairly often, but not too often.

Please let me know how it goes :)

**Comment by ufrisk** [comment]
Since I haven't heard anything back on this issue I'll assume it's resolved and your fix is working.
