### ISSUE TITLE
Similar issue around amd systems

### ISSUE THREAD

**Issue by erick7388** [ufrisk/pcileech#176]
FPGA: TINY PCIe TLP algrithm auto-selected!
LcMemMap_AddRange: 0000000000000000-000000000009ffff -> 0000000000000000
LcMemMap_AddRange: 0000000000100000-00000000ffffffff -> 0000000000100000
LeechCore v2.1.4: Open Device: fpga
VmmWinInit_TryInitialize: Initialization Failed. Unable to locate valid DTB. #2
VmmProc: Unable to auto-identify operating system for PROC file system mount.
         Specify PageDirectoryBase (DTB/CR3) in -cr3 option if value if known.
MOUNT: INFO: PROC file system not mounted.

**Comment by erick7388** [comment]
Could I get a little help with this error, not sure what the problem is but I seen you ran into the problem a little while ago.

**Comment by ufrisk** [comment]
You would need to specify a memory map file on AMD systems containing the memory layout. `-memmap <memmap_file.txt>`.

It looks something like this:
```
   #         Base            Top
--------------------------------
0000         1000 -        9efff
0001       100000 -       101fff
0002       103000 -     dffeffff
0003    100000000 -    19fffffff
```

The memory map ranges are different for your computer. You can view them in Microsoft Sysinternals RamMap.

![image](https://user-images.githubusercontent.com/18221464/142763635-b41f9304-2797-49a1-aea5-f209308f08ac.png)


If you're lucky it may work with `-memmap auto` - but going with the ram map file approach is probably the best.

Reason for this is that AMD/Thunderbolt stops working if you make a DMA read to an address not in that map. And there is no good way of detecting which ranges may be in the map or not. I'll try to put up a guide page about this as well.

Please let me know how it goes.

**Comment by erick7388** [comment]
resolved

**Comment by ufrisk** [comment]
I'm happy to see this issue is resolved. I'm closing it. Also, since more people have asked about this I've put up a short guide entry at https://github.com/ufrisk/LeechCore/wiki/Device_FPGA_AMD_Thunderbolt
