### ISSUE TITLE
Windows 10 on ARM64 support 

### ISSUE THREAD

**Issue by sidd-kishan** [ufrisk/pcileech#177]
Please let us know when can we have an ARM64 version for Windows on ARM OS. We can help you test We have Windows on Rasberry Pi setup. Please pursue it we at Windows on Rasberry Pi community will be glad to extend support in testing your drivers and tools for ARM64.

**Comment by ufrisk** [comment]
Hi,

Thanks for contacting me about this. I some time ago looked into this as well but I have two unmet dependencies unfortunately.

1. For PCILeech DMA access on the FT601 driver from ftdichip. https://ftdichip.com/drivers/d3xx-drivers/

2. For the virtual file system (used by PCILeech mount and MemProcFS memory analysis) dokany: https://github.com/dokan-dev/dokany

As soon as these two dependencies are met my intention is to support Windows on ARM. But there isn't much I can do about this.

**Comment by sidd-kishan** [comment]
The 2nd Dependency seems to be met please check.

**Comment by ufrisk** [comment]
Update,

I just released the MemProcFS memory analysis project for Windows 10/11 for ARM64. You'll now be able to analyze memory dump files on your ARM64 Windows 10/11 computer. (Analyzing memory dumps from ARM64 systems are not yet supported though - but I hope to add it).

Sadly there is still no USB driver from ftdichip.com so no DMA memory acquisition until then (and reason why I haven't done PCILeech yet).

Info at: https://github.com/ufrisk/MemProcFS/wiki/_ARM64

**Comment by ufrisk** [comment]
This is working since some time ago. X64 binaries will work just fine with minimal performance impact.

Also analyzing ARM64 Windows systems are now supported as well so I'm closing this issue.
