### ISSUE TITLE
About Artix 7 XC7A35T and XC7A75T

### ISSUE THREAD

**Issue by BurcakAsal** [ufrisk/pcileech#178]
Hi,

I want to consult about DMA performance and stability difference between XC7A35T and XC7A75T fpga chips. I know that XC7A75T is considerably powerful than XC7A35T but, ultimately I think that USB3/USB-C interfaces bottleneck that performance difference and these two chips have more or less same memory retrieval or writing speeds with USB3/USB-C , and finally because these two chips are same Artix-7 brand, I assume that they are produced with same material, consequently they should have same stability with respect to reading/writing memory operations on constant using, I am wondering that whether my assumption on this issue is correct or not.

Regards

**Comment by ufrisk** [comment]
Hi,

The PCIeScreamerR04 and the EnigmaX1 are both good stable boards.

As far as performance the 75T has larger internal memory which is used for buffering larger reads. If doing larger reads performance will be slightly higher on the 75T. If doing smaller reads the performance will be the same.
