### ISSUE TITLE
Stopped working without any changes done

### ISSUE THREAD

**Issue by Frement** [ufrisk/pcileech#179]
This same issue was randomly happening from time to time, but was fixed simply by shutting the system down and starting it up again.

But now it no longer works at all.

```
DEVICE: FPGA: ScreamerM2 PCIe gen2 x1 [300,25,500] [v4.8,0700] [ASYNC,NORM]
FPGA: TINY PCIe TLP algrithm auto-selected!
VmmWinInit_TryInitialize: Initialization Failed. Unable to locate valid DTB. #2
VmmProc: Unable to auto-identify operating system for PROC file system mount.
         Specify PageDirectoryBase (DTB/CR3) in -cr3 option if value if known.
MOUNT: INFO: PROC file system not mounted.
```

```
FPGA: TINY PCIe TLP algrithm auto-selected!
LcMemMap_AddRange: 0000000000000000-000000000009ffff -> 0000000000000000
LcMemMap_AddRange: 0000000000100000-00000000ffffffff -> 0000000000100000
LeechCore v2.5.2: Open Device: fpga
 Memory Map:
 START              END               #PAGES


 Current Action: Probing Memory
 Access Mode:    Normal
 Progress:       4096 / 4096 (100%)
 Speed:          87 MB/s
 Address:        0x0000000100000000
 Pages read:     0 / 1048576 (0%)
 Pages failed:   1048576 (100%)
Memory Probe: Completed.
```

**Comment by ufrisk** [comment]
which dma harware are you using?
do you have it directly connected to the target system via PCIe or are you connecting via Thunderbolt?
do your target system have AMD or Intel CPU?

**Comment by Frement** [comment]
Device: ScreamerM2 PCIe gen2 x1
I tried in M.2 slot, and with M.2 adapter to a normal 16x PCIe slot.
Intel CPU.

I reflashed a new version to the device and it seems to have fixed the issue, so I guess my current question would be what can cause the firmware to bork?

**Comment by ufrisk** [comment]
I don't know what may have caused this temporary issue, but it's good to see it went away after the upgrade. I don't see how a flashed device would stop working all of a sudden and then jump to life after a re-flash. Maybe it was some temporary glitch.

It looks a bit similar to the Thunderbolt / AMD issues as per: https://github.com/ufrisk/LeechCore/wiki/Device_FPGA_AMD_Thunderbolt Maybe it would have helped setting a memory map for your now resolved issue as well. Maybe not. But it's nice to see it's working again.

Best Wishes with your DMA attacking :)

**Comment by Frement** [comment]
Forgot to mention I did set a memory map also, which didn't really change anything. The device seemed to fail on every read regardless.
