### ISSUE TITLE
Is there any inherent limitation to connecting to a FPGA device from the same system it is connected to?

### ISSUE THREAD

**Issue by rlewkowicz** [ufrisk/pcileech#181]
Just for the ease of development and general convenience, I run a usb cable from the screamer device to the same pc the screamer is plugged into. It shows in device manager  as a super speed fifo bridge but I get, PCILEECH: Failed to connect to the device. I am able to connect from an external linux system, but due to certain tool chain limitations/ system compatibility it would be easier If I could do it local to it's self. If that makes any sense. I do have the proper USB drivers along side the pcileech binary.

**Comment by ufrisk** [comment]
what does it say if you do `pcileech display -min 0x1000 -v -device fpga`?

does the device show up as a USB device in device manager, it should be named something like FTDI superspeed bridge.

**Comment by ufrisk** [comment]
![image](https://user-images.githubusercontent.com/18221464/148285373-f89aaaf8-0f2f-4fda-ad2c-0aaea69b965e.png)

**Comment by rlewkowicz** [comment]
```
PS C:\Repos\leech\leech-main> ./pcileech.exe display -min 0x1000 -v -device fpga

DEVICE: FPGA: ERROR: Unable to connect to USB/FT601 device [0,v0.0,0000]
PCILEECH: Failed to connect to the device.
```

I'll fire up my other windows box and see if I can make it work

**Comment by rlewkowicz** [comment]
No good there either. My FPGA software is probably almost a year old at this point. It could be that? It's odd that the linux version works. I suppose next step is maybe see if I can find older FTD3xx driver or something. I know this worked in the past, I shelved all my hobby projects for a while and wiped the old drive in the process.

**Comment by ufrisk** [comment]
It's not the FPGA gateware that is old. It should work fine, and as you mention it works on Linux. It doesn't hurt to upgrade it though.

Make sure the FTDI drivers are updated with the most recent ones. both the FTD3XX.dll alongside PCILeech and also try update the driver in the device manager with the packages from https://ftdichip.com/drivers/d3xx-drivers/  Maybe there are some issues around that. If the FT601 shows up in device manager I have a hard time seeing it could be the cable.

I double checked this on the most recent PCILeech I have on my github and it works on my computer :\

**Comment by rlewkowicz** [comment]
This was me being dumb. I did run their driver installer, but it just didn't take I guess. I had to download the driver with the inf, and specifically select the windows 10 folder from the driver installation

**Comment by ufrisk** [comment]
Thanks for the update and awesome to see the issue is resolved.

Usually the driver downloads and installs itself automatically from WIndows Update, but sometimes it's not working. Anyway super nice to see it's resolved :)
