### ISSUE TITLE
Unable load the PCI leech USB 3380 kernel driver on Yocto OS

### ISSUE THREAD

**Issue by sridhaleech** [ufrisk/pcileech#190]
Hi ,

Can someone help  me to load the driver for PCI leech USB 3380 device in Yocto OS.

If possible provide the steps to follow ? for Yocto OS 5.15 version ?

Thanks ,

Sridhar

**Comment by ufrisk** [comment]
The USB3380 "kernel driver" is only required for flashing it. Do it on some old ubuntu once and you're done with it.

After that it should work with regular user-mode libusb. You may have to run as root or change permissions on the USB device though. Also make sure the net2280 device driver isn't loaded (you may have to blacklist it in etc modules blacklist.

For PCILeech nowdays I do not recommend the USB3380 though unless there are strong reasons to use it. It's only capable of accessing memory below 4GB and isn't quite as stable as the FPGAs. FPGAs are currently sold out but I've hard shop.lambdaconcept.com might have them restocked within the next few weeks.

**Comment by sridhaleech** [comment]
Hi , Thanks for your valuable reply ..
This test recommended for us -  USB 3380 device only as of now .And we are planning to test FPGA also Soon .
Now we need to finish test with USB 3380 device. 

I followed setup for installing kernel driver 
1. Connected PCIe leech 3380 device with startech PCie mini adaptor on my target system.
2. Now Loading the our OS (Linux Yocto 5.15 V ).
3. Now checking "whether PCIe leech 3380 driver loaded or not using "lspci"
4. I'm seeing USB leech 3380 driver not loaded ( it shown  "USB controller" Broadcom  Inc ,its mean no kernel driver ) 
5. I'm trying to load driver using  USB3380 flash folder under linux.
6. when do "" getting this " insmod: ERROR: could not insert module pcileech_flash.ko: Invalid module format"
![image](https://user-images.githubusercontent.com/97678866/165019584-92e54a03-db34-440e-aaf9-35833c73421f.png)

how to install pci leech driver .For Linux ( Yocto OS ,i don't to understand ,is any easy way to follow ?

Kindly help to me fix this issue ?

Thanks 
Sridhar

**Comment by sridhaleech** [comment]
Thanks will check and update ..

**Comment by sridhaleech** [comment]
Thanks .
will try with Ubuntu version 18.04 and update to you .

**Comment by sridhaleech** [comment]
> Hello,
> 
> I have a flash instruction at: https://github.com/ufrisk/pcileech/tree/master/usb3380_flash/linux
> 
> I'm not sure it will work under Yocto OS. Can you please test this on an older Ubuntu version, such as 18.04. You only need to do the initial flash once. Flashing from live Ubuntu will work (you may have to apt-get gcc and such first though). Also make sure security boot is not enabled so that the kernel module will be loaded.

Hi, Once after flash this USB3380 flash ROM ,will it work windows OS ?

**Comment by ufrisk** [comment]
Yes, you only need to flash it once to enable the USB port. After that it will work fine on Windows (provided that you install the Google Android driver I point to in the instructions).

**Comment by sridhaleech** [comment]
we tried below and need some confirmation 
===================================
Flashing in Linux must be done as root. Download the source code for the flash kernel module to build. The files are found in the pcileech_flash/linux folder and are named: pcileech_flash.c and Makefile. The card must be connected to the Linux system doing the flashing via PCIe.
•	cd /pathtofiles
•	make
•	[ insert USB3380 hardware into computer ]
•	insmod pcileech_flash.ko
======================================
After successfully ran insmod command “Pcie leech USB3380 device” glowed bule color led and then we did power-cycled & Re-inserting the leech device in the computer.
Power ON and Booted to Ubuntu OS 18.04 v, Now the bule color led is not glow.
Now we want to know, whether my pci leech device card got flashed or not ? how to confirm it ?

**Comment by sridhaleech** [comment]
We are able to see device using lspci -n  and thanks

01:00.0 0c03: 14e4:16bc (rev ab)

**Comment by sridhaleech** [comment]
Hi ,
here one more ask.

Without flashing the USB3380 leech card also shown "01:00.0 0c03: 14e4:16bc (rev ab)"

now i want confirm the pci leech driver loaded or not in OS level.
how to confirm ? current system enumeration screenshot below -
![leech_pci](https://user-images.githubusercontent.com/97678866/168206236-17f8de2e-705a-4781-8f81-adc8185ac582.png)

I could see driver install  in windows OS & after install driver we see under pci root port "leech enumeration " screenshot below , Same like i want confirm in Ubuntu and how to check ? 

![image](https://user-images.githubusercontent.com/97678866/168205973-bc4a8a4f-f745-4449-b53b-096f9d377f47.png)

**Comment by ufrisk** [comment]
It's correctly flashed if the computer will react to the USB being plugged in. (note that it will first have to be plugged in to the mini-PCIe for it to receive power). Install the android drivers to get the USB working as per instructions (if running on Windows). Then you're good to go. No need to do anything about drivers for the mini-PCIe side of things. Good Luck with everything 👍

**Comment by ufrisk** [comment]
Correct. Once flashed no driver should be needed on the PCIe side. On the USB side you'd need to have libusb installed and run as root or have correct permissions on the libusb device under `/dev/`

**Comment by sridhaleech** [comment]
Hi,
Is there any "libusb" source files link to install and installation instructions  ?

**Comment by ufrisk** [comment]
Please try `sudo apt-get install make gcc pkg-config libusb-1.0 libusb-1.0-0-dev fuse libfuse-dev openssl libssl-dev lz4 liblz4-dev`

It's working on supported and tested OS (Ubuntu 18.04/20.04/22.04). It should work on other Linux OS as well, but I'm unable to officially support them all.

About how to install libusb from source please ask/consult the libusb project for that. I'm unable to support all dependencies in this open source project and do even more unpaid support.
