### ISSUE TITLE
FPGA Spartan 6 SP605 is not detected this is for 64 bit address - DMA 

### ISSUE THREAD

**Issue by sridhaleech** [ufrisk/pcileech#191]
Hi ,

i 'm try to enable FPGA Spartan 6 SP605 with FT601 using the link (https://github.com/ufrisk/pcileech-fpga/tree/master/sp605_ft601)

while i'm trying to flash the FPGA card.i could not make it work. Once after installed --> 13.4 v  "Xilinx ISE Development Environment",when open the ISE app , automatically getting closed.

i have purchased newly .

i'm trying now in windows OS 64 bit (enterprise ) and i wany to try in Yocto OS also.

But first i want try in windows OS supported system.

can someone assist me to enable this FPGA card on my testing system ? 

Last two week back i have purchased for my testing ( DMA ).

**Comment by ufrisk** [comment]
The Xilinx ISE is quite old and crappy. Your best shot for an easy flash is probably to do it on some old install of Windows 7.

Once flashed the device should work fine on both Windows and Linux.

**Comment by sridhaleech** [comment]
Once flashed the device should work fine on both Windows and Linux --> You mean after flash the device in Windows 7 then we can change the Win10 OS and linux ?

**Comment by ufrisk** [comment]
Yes, once flashed you should be able to use it from Linux and/or Windows 10. You will only need to flash it once.

**Comment by sridhaleech** [comment]
Good Morning and thanks .
Sorry to ask you . if you know the flashing link ,can you provide me ? i have one link wich is given by xilinx web.

if possible ,can provide easy way to do this flashing method ?

**Comment by ufrisk** [comment]
You'd need to create an account, log in, download the Xilinx ISE and install it and then flash according to instructions.

I'm aware that the ISE is an old horrible piece of software. Personally I really dislike it. I'm not able to support every step of the installation, and it's really too bad Xilinx is no longer supporting the Spartan6 in a good way. But things are as they are unfortunately. For guidance how to install and use the ISE I'm afraid you'll have to consult Xilinx forums.

**Comment by sridhaleech** [comment]
Hi , Can suggest latest pci leech 64 bit model with winOS and USB Type A  support device ?

Currently can we do DMA with FPGA Spartan 6 SP605 card in WinOS using pci leech SW ?

**Comment by ufrisk** [comment]
As long as the SP605 (with the FT601 add-on board) is properly flashed PCILeech should work on both Windows and Linux. It even works on the 64-bit Raspberry PI.

**Comment by ufrisk** [comment]
I'm closing this issue due to old age.
