### ISSUE TITLE
PCIe leech USB 3380EV can accessing the 64 bit address  - This is Issue

### ISSUE THREAD

**Issue by sridhaleech** [ufrisk/pcileech#197]
Hi ,

I'm doing the dumping certain memory ranges and in that covered  64 bit address also like  " 0x100000000" 

And able to do the 1 pages dumping with 64bit address range on PCI leech USB3380EV connected.

I have noticed that, there is a HW limitation from leech USB 3380EV and  max address can be dump pages till 32 bit address range . like upto 0xffff ffff

But here i can dumping 1 page of 64 bit address, i'm not sure. Ideally its should not be dump 64 bit address range right ?
 pls refer the below dumping 1 page range ( 64 bit ranges )

C:\Users\CBRD\Desktop\pcileech_files>pcileech.exe dump -min 0x100000000 -max 0x100004000 -force

 Current Action: Dumping Memory
 Access Mode:    DMA (hardware only)
 Progress:       0 / 0 (100%)
 Speed:          4 kB/s
 Address:        0x0000000100000000
 Pages read:     0 / 1 (0%)
 Pages failed:   1 (100%)
Memory Dump: Successful.

Can you pls help me to clarify this ? 

Thanks / Sridha

**Comment by sridhaleech** [comment]
Thanks and still it is a issue from the leech USB3380EV card side  ? if i'm not wrong .

Because 0x100000000 address is 64 bit and its should not dump 64 bit address by leech USB 3380 right ?

I'm looking for FPGA card for accessing 64 bit address ranges .

**Comment by ufrisk** [comment]
Yes, thanks for reporting. I'll change the message to Failed if all memory pages are failed.

**Comment by ufrisk** [comment]
I'm closing this issue due to old age.
