### ISSUE TITLE
Build PCILeech SP605/FT601 - FIle missing 

### ISSUE THREAD

**Issue by sridhaleech** [ufrisk/pcileech#198]
Hi ,

Preparing the setup enabling FPGA SP605 with FT601 connected for access 64 bit memory .

I have installed ISE 13.4 Ver and trying to build.

i'm unable to find the step -3 file. when i click the "pcileech.mcs" and  getting " reset " could you help me to find ?

========
Flashing:
1. Ensure the both the SP605 and FT601 is configured correctly with correct jumpers and switches. Please see images above.
2 Install Xilinx ISE Development Environment.
3 Build PCILeech SP605/FT601 (see below) alternatively download and unzip pre-built binary: [pcileech.mcs] 
(https://mega.nz/#!QPJm3bLT!8NrEBR-yLn-Qur7VkqsnahiPgkGp2nWw4Z9XWLLamxo).
4 Open ISE Design Suite 64-Bit Command Prompt.
5 Make sure the JTAG USB cable is connected.
6 Run flash.bat to flash the bitstream onto the SP605.
7 Finished !!!

**Comment by ufrisk** [comment]
It seems to be working for me though. This is on a clean win7 install. I'm sorry that this ISE is so darn backwards, but I'm not supporting that tool, xilinx is...
![ise-1](https://user-images.githubusercontent.com/18221464/177596422-f8ad5508-f66c-4316-b9f4-75039156f7dd.PNG)
![ise-2](https://user-images.githubusercontent.com/18221464/177596436-991f694b-c34c-4dfc-aa98-2c18cac825df.png)
![ise-3](https://user-images.githubusercontent.com/18221464/177596447-50a5bd2d-6b3d-46ae-9867-6f8d6d89da6d.PNG)

**Comment by sridhaleech** [comment]
Thanks for the update .

Will try out it in our system .

**Comment by sridhaleech** [comment]
Hi,
I ran the "Build.bat" file and we unable to create the .mcs file.

if have time , Kindly review the below picture of "build.bat" issue and suggest us ? 

![Build_issue](https://user-images.githubusercontent.com/97678866/178680426-ac6c1410-a5df-4805-b42a-0820abbfc566.JPG)

**Comment by ufrisk** [comment]
Did you start the script from the `ISE Design Suite 64 Bit Command Prompt` as I show in the screenshots?

Or on the WinXP the 32-bit one I guess. I have never tried this on Windows XP though, only on Win7 64-bit.

**Comment by sridhaleech** [comment]
Hi ,
i have tried with Win 7 pro OS and while doing "Flash.bat" getting below issue .

![Flash_issue](https://user-images.githubusercontent.com/97678866/178926571-4d3c9db2-a10e-421e-849d-83860329cfb6.JPG)

**Comment by ufrisk** [comment]
the path may be too long and run into the windows path limitation of 260 chars. try put the project in c:\temp\sp605_ft601 and rebuild from scratch.

**Comment by ufrisk** [comment]
I'm guessing this issue was resolved. I'm closing this issue due to old age.
