### ISSUE TITLE
Speed Issue 

### ISSUE THREAD

**Issue by Dfaker-HK** [ufrisk/pcileech#200]
I recently bought screamer dma, and I tried to test it out through dumping memeory on pc, but then I found out that the speed is very low(70mb/s), then I tried to switch cable, pcie slot etc. all dosent work, but when I switch the pc running pcileech, the speed just become normal(>150mb/s), at this point, I think maybe it is the pc problem, but the first pc I am using is a i7 8665u and it's cpu usage dosent come to 100% when I run mem dump, is there any possible mistake I made so the speed is so slow? 
<pre>Memory Dump: Initializing ... Done.
 Current Action: Dumping Memory
 Access Mode:    Normal
 Progress:       2176 / 17139 (12%)
 Speed:          72 MB/s
 Address:        0x0000000188000000
 Pages read:     557056 / 4387584 (12%)
 Pages failed:   0 (0%)</pre>

**Comment by ufrisk** [comment]
I agree this is quite slow. But it's fast enough so it's not an issue with the USB cable.

Are you by any way dumping to a slow HDD?

Also performance on Linux are slower than when running PCILeech on Windows due to driver issues.

**Comment by rancheng** [comment]
if you suffer from speed, and got only half of the speed, like 70mb/s, check if you are  using gigabyte motherboard, I switched the motherboard to Asus its normal again, don't use gigabyte motherboard, repeat, DONT USE GIGABYTE motherboard!!!

**Comment by ufrisk** [comment]
I'm closing this issue due to old age and since I haven't heard back on the issue I trust that it's resolved.
