### ISSUE TITLE
How to save the Dumping Memory log to text format using PCIleech command ?

### ISSUE THREAD

**Issue by sridhaleech** [ufrisk/pcileech#202]
Hi ,

Actually, I need to save the below "Dumping Memory" log result as text format using PCIleech any command ?

![image](https://user-images.githubusercontent.com/97678866/180364149-d19ce1dc-6c49-4d5b-8f99-a99d051bc642.png)

By default ,log will be generated .RAW format.I'm unable open and see the log.

Currently i'm seeing the "Dumping Memory" result in CMD window page.

Is there any way to generate the result as text format ?  using PCI leech SW ?

![image](https://user-images.githubusercontent.com/97678866/180364149-d19ce1dc-6c49-4d5b-8f99-a99d051bc642.png)

**Comment by ufrisk** [comment]
No, there is no functionality to do this directly.

If you wish to copy the text you could start pcileech from another program and then grab the text.

You may also use the [LeechCore](https://github.com/ufrisk/LeechCore/) library to code your own memory dumping application.

**Comment by sridhaleech** [comment]
Thanks. 
Is there any way to check the .RAW output log using any SW for decode ?
And How to check the "Page read" and "Page Failed" result in the .RAW log using any decode SW ?

Thanks adavance.

**Comment by ufrisk** [comment]
If you have any successful pages it will show which memory ranges are successful in the text. You'd have to parse that if you're not using the API.

In this case it seems like everything is failed so there will be no successful data.

**Comment by sridhaleech** [comment]
Hi Frisk,

If you don't mind. What you mean, I didn't get this  --> You'd have to parse that if you're not using the API

Our ask is -->  How to open PCIleech output .RAW file ?

Is there any software to Open .RWA file or how ?

**Comment by ufrisk** [comment]
Please use MemProcFS (on Windows dumps) or Volatility (on Windows, Linux, Mac dumps).
