### ISSUE TITLE
"DEVICE: FPGA: ERROR: Unable to connect to USB/FT601 device [0,v0.0,0000]" with Screamer PCIe Squirrel on Windows 11

### ISSUE THREAD

**Issue by retro-git** [ufrisk/pcileech#204]
Hi, I recently purchased a Screamer PCIe Squirrel which is pre-flashed with the pcileech gateware. I disabled VT-d in BIOS, installed the device into a PCIe slot, and downloaded pcileech along with FTD3XX.dll (I am using Windows 11). I can see that the PCIe Squirrel shows up in Device Manager as an Ethernet Controller with no driver. Also, I see the USB device in Device Manager like so: 

![image](https://user-images.githubusercontent.com/43223593/184697084-8908541e-b766-43ca-a005-15f6a4ea7ca9.png)

Then I ran `pcileech probe -device fpga -v`. However, every time I simply get the following error message:

`DEVICE: FPGA: ERROR: Unable to connect to USB/FT601 device [0,v0.0,0000]
PCILEECH: Failed to connect to the device.`

One thing worth noting is that I currently don't have a secondary PC to use as the attacker, so I am plugging the USB cable from the Squirrel into the same PC as I have the PCIe card installed into - I'm unsure if this is an issue. Also worth noting is that I am using a Gigabyte Z390 Aorus Pro WIFI motherboard, and while the PC is turned on, I see two green LEDs on the left and right side of the PCIe card constantly on (the one in the middle is off).

At this point I'm very unsure in how to go about troubleshooting the issue any further, so any help would be greatly appreciated. Thanks very much for reading.

**Comment by ufrisk** [comment]
Issue is with USB communication, possibly because you have some strange usb serial converter installed. You're supposed to have a driver for FTDI FT601 USB 3.0 Bridge Adapter - this should install automatically from windows update at first plugin. You may also download the driver from [FTDI](https://www.ftdichip.com/Drivers/D3XX/FTD3XXDriver_WHQLCertified_v1.3.0.4.zip)

![image](https://user-images.githubusercontent.com/18221464/184731549-73348465-ef8a-4dfc-80ae-b589ebfa72b2.png)

**Comment by retro-git** [comment]
Thanks very much for the response. Upon looking into it a bit further, it seems that when I plug the USB device in, it actually appears as 4 different devices in Device Manager - USB Serial Converter A/B/C/D: 

![image](https://user-images.githubusercontent.com/43223593/184744655-ff9ed2fc-4925-4696-9dd1-8b8d8205ccef.png)

It seems it is somehow being recognised as a USB to 4x serial converter, like this https://www.amazon.co.uk/Digitus-1-5m-USB-RS232-Cable/dp/B009H06O7C?

I downloaded and manually installed the FTDI drivers you linked for each of these 4 devices, but it did not fix the problem - I get an error saying the device failed to start:

![image](https://user-images.githubusercontent.com/43223593/184745936-194dd2c3-4f80-4318-bc04-cb283ea7d4da.png)

I'll install Ubuntu 20.04 and try that out later.

**Comment by ufrisk** [comment]
Oh, btw are you having the usb cable in the data port? If having it in the update port it will show the serial converters I think. Try the data port instead.

**Comment by ufrisk** [comment]
@retro-git how did it go if you changed the usb-c port on the screamer board?

**Comment by retro-git** [comment]
Well, now I feel very stupid - I thought I had tried both ports before but in any case that did indeed solve the problem. Thanks very much.

**Comment by ufrisk** [comment]
Nice to see the issue is resolved. Best wishes with your DMA attacks.
