### ISSUE TITLE
Issue with valorant game on my squirrel/r03/r04

### ISSUE THREAD

**Issue by echostationunderground** [ufrisk/pcileech#205]
I thought maybe here my card had died but I have a squirrel and a r03 and a r04......and i tried it on all of them. Starting today my cards seem to stop working....but only when the valorant game (vanguard anti-cheat doing IOMMU?) is open?  Some things i have done..

-Disabled IOMMU in bios
-Disabled preboot DMA prevention in bios
-Disabled kernel DMA protection in Windows

If I try pci screamer dump command to confirm it... you can see in the screenshot.

![screamer](https://user-images.githubusercontent.com/111822181/186044029-8c4afd8f-ceb3-4b21-a5c1-5dea93a77734.PNG)

**Comment by ufrisk** [comment]
I'm not doing cheats and the pcileech project is not aimed at cheats (even tho I know it's being used for it) so I'll close this issue.

Generally if the anti-cheat have started to use the IOMMU disregarding user bios settings it's not much you can do about it. You can try to enable VT-d in BIOS so that Windows will pick up on it (and hog it from the anti-cheat) often it works anyway if the computer is unlocked. Or find a white listed device and clone it instead. Once IOMMU fully enabled as it seems like it is in this case it's game over.

**Comment by itsgamerdoc** [comment]
![giphy (11)](https://user-images.githubusercontent.com/65831830/186214200-535a00fc-e6d5-4fd2-92c2-dee65349773c.gif)

**Comment by 0xGabriella** [comment]
im sure it wont be stable enough for a long-term implementation due to so many false-positive possibilities.

**Comment by S1ckZer** [comment]
works fine Enable "virtualization-based protection of code integrity"

**Comment by echostationunderground** [comment]
@0xGabriella Hello thx for the reply. Can u give more context here I tried with engaging HVCI with core isolation feature on my dma computer. I still have this issue though. Am I missing something?

**Comment by S1ckZer** [comment]
HVCI activated
Platform Security Level - Safe Start
With UEFI-Lock activated

don't change anything else

cmd admin gpupdate /force

restart pc and have fun

**Comment by echostationunderground** [comment]
@S1ckZer still happens with these settings too :| could it be Windows 11? what windows version u on?

**Comment by S1ckZer** [comment]
I'm on the latest Windows 10 version. Windows 11 is maybe different

**Comment by AiMLOC** [comment]
> I'm on the latest Windows 10 version. Windows 11 is maybe different

Hey still working on win 10? Do you mind sending me what you did I don't see it anymore.

**Comment by echostationunderground** [comment]
I downgrade to Win 10 today ver 19044. Have they started to use IOMMU again? I cannot r/w memory now when the game starts.It worked for a couple days earlier.

**Comment by AiMLOC** [comment]
> @AiMLOC
> 
> I downgrade to Win 10 today ver 19044. Have they started to use IOMMU again? I cannot r/w memory now when the game starts.It worked for a couple days earlier.

Yes they have looking for a solution ATM

**Comment by dcassets** [comment]
Same thing here. Just gave it a test on Windows 10 21H2.
Game closed, reading no problem.
Game open, reading failed
Game closed, reading no problem

Using Raptor with custom firmware from DamnCheaters.

**Comment by dcassets** [comment]
@echostationunderground i dont own a cheat for Valorant. But can you test to start Valorant, directly start cheat and read memory and keep the dma connection open.

It looks that when youre keep reading memory and start Valorant the dump is stil working fine.
Only after you start dumping when the game is started for around 30 seconds the dump fails.

**Comment by S1ckZer** [comment]
> @echostationunderground i dont own a cheat for Valorant. But can you test to start Valorant, directly start cheat and read memory and keep the dma connection open.
> 
> It looks that when youre keep reading memory and start Valorant the dump is stil working fine. Only after you start dumping when the game is started for around 30 seconds the dump fails.

Will not work they force loading IOMMU

**Comment by dcassets** [comment]
> > @echostationunderground i dont own a cheat for Valorant. But can you test to start Valorant, directly start cheat and read memory and keep the dma connection open.
> > It looks that when youre keep reading memory and start Valorant the dump is stil working fine. Only after you start dumping when the game is started for around 30 seconds the dump fails.
> 
> Will not work they force loading IOMMU

Sure? I was dumping memory and could start and play without problems and dumping was stil working

**Comment by S1ckZer** [comment]
This is so easy to fix.

 after I have found another possibility to use dma I will share my first fix you and this rat's. 


Is German but you will find out

![unknown](https://user-images.githubusercontent.com/93842747/188427763-323e1d56-3ad4-414c-8923-bb5b950e29c4.png)
Step 2. gpupdate /force
Step 3. Restart Pc

**Comment by dcassets** [comment]
> This is so easy to fix.
> 
> after I have found another possibility to use dma I will share my first fix with you and this rat's.
> 
> Is German but you will find out
> 
> ![unknown](https://user-images.githubusercontent.com/93842747/188427763-323e1d56-3ad4-414c-8923-bb5b950e29c4.png) Step 2. gpupdate /force Step 3. Restart Pc

Nice found. Can give it a try in a few hours. Wil post English for the rest.

**Comment by echostationunderground** [comment]
I jhave tried this on 10/11 and it does not work for either case. It is also very annoying to escape from UEFI lock because you must delete FW variables to unlock agian. If this works for you that is great and also very strange. Does not work for me on 2 computers,

**Comment by S1ckZer** [comment]
> I jhave tried this on 10/11 and it does not work for me either case. Very annoying to escape from UEFI lock because you must delete variables to unlock annoying shit agian. If this works for you that is great and also very strange. Does not work for me on 2 computers,

All I can say is try it until it works. 
Works for 15 other people too.

**Comment by CODEX4096** [comment]
![valorant-cheater](https://user-images.githubusercontent.com/43946069/188603655-7e2ae4a1-73e0-41b0-a4ae-f44079b8a74f.gif)

**Comment by dcassets** [comment]
> I jhave tried this on 10/11 and it does not work for me either case. Very annoying to escape from UEFI lock because you must delete variables to unlock annoying shit agian. If this works for you that is great and also very strange. Does not work for me on 2 computers,

Same here. No way to get it working.

**Comment by waryas** [comment]
That's what you get for buying devices for cheating that aren't intended for cheating instead of trying to get around it in a smarter way.
Some people don't learn.

**Comment by FocuzJS** [comment]
For sake of correctness, I'll just leave this here: https://www.unknowncheats.me/forum/anti-cheat-bypass/584445-vanguard-prevent-dma.html 
You are all far from correct.
