### ISSUE TITLE
USB3380EVB check if it works

### ISSUE THREAD

**Issue by briskspirit** [ufrisk/pcileech#207]
So I've got USB3380EVB miniPCIe board. Flashed it with raspberry Pi CM4 board(has PCIe x1, kernel module loaded fine and it blinked leds). 
Device is being detected by my Win11 PC, I've successfully installed Google ADB driver for it. But other than that I can't check if it really works (still plugged into RP CM4 target). I know that arm is not supported, but is there a way I can check that usb3380 really works/alive? Thought I should still be able to read raw memory or probe it, no? 
Thank you for your great work by the way!

**Comment by ufrisk** [comment]
I haven't looked into doing DMA on ARM. It should work, but I think it may have the IOMMU activated so DMA is blocked.

Best way is probably to do a read test on a random address `pcileech.exe display -min 0x1000` (read some memory from physical address 0x1000).

If you have the chance to try it on an x86 machine as well running some older OS when logged on (i.e. win10 or ubuntu 20.04 or older) it would be good as well.

Please let me know how it goes.

**Comment by ufrisk** [comment]
I'm closing this issue due to old age.
