### ISSUE TITLE
VMMDLL_Initialize on x86

### ISSUE THREAD

**Issue by unemknip** [ufrisk/pcileech#215]
Hello, I am making a program for x86 architecture, I recompile all the necessary files for x86 (leechcore, vmm)

But when VMMDLL_Initialize is called, it crashes because I catch nullptr and GetLastError says 193 which indicates that this application is not under win32.

I tried to figure out my mistake on my own, but I'm only at the stage of learning all the nuances related to DMA, so I thought I'd ask you :)

**Comment by ufrisk** [comment]
As you may have noticed I'm not really doing as much testing on 32-bit x86 as I should do. It's a bit of a 2nd class citizen.

I guess you'd need to run it on 32-bit x86 due to your CPU architecture? If you're able to run MemProcFS on 64-bit it's highly recommended. 64-bit MemProcFS is able to analyze 32-bit memory as well (it does not run on 32-bit only CPUs/OS'es though).

Are you targeting 32-bit Windows or Linux?

**Comment by unemknip** [comment]
> As you may have noticed I'm not really doing as much testing on 32-bit x86 as I should do. It's a bit of a 2nd class citizen.
> 
> I guess you'd need to run it on 32-bit x86 due to your CPU architecture? If you're able to run MemProcFS on 64-bit it's highly recommended. 64-bit MemProcFS is able to analyze 32-bit memory as well (it does not run on 32-bit only CPUs/OS'es though).
> 
> Are you targeting 32-bit Windows or Linux?

Thanks for your answer, I need this architecture because it is running the process I am connecting to, I am using Windows

**Comment by ufrisk** [comment]
It's working fine for me. Maybe you mix 32-bit and 64-bit dlls somewhere? Please find an updated x86 build attached below.

[MemProcFS_files_and_binaries_v5.2.0-win_x86-20221115.zip](https://github.com/ufrisk/pcileech/files/10077501/MemProcFS_files_and_binaries_v5.2.0-win_x86-20221115.zip)

**Comment by unemknip** [comment]
Everything works fine, I made a mistake only in my code, thanks for your answer and sorry for wasting your time.

**Comment by ufrisk** [comment]
Thanks for letting me know and best wishes with your project :)
