### ISSUE TITLE
Writing mouse input via DMA?

### ISSUE THREAD

**Issue by MrCoInSanity** [ufrisk/pcileech#218]
Hello, I'm curious on how I would send mouse x, y cords to windows via DMA?

I've been doing some research but I thought I may aswell ask here because it seems like a general question that may get asked alot and already answered.

My thought is to write to the input buffer, but I'm afraid I'm still looking into it. 

Best Regards, Joel.

**Comment by ufrisk** [comment]
I'm not sure it's possible to easily send cursor positions to certain windows, but I'm fairly certain it's possible to induce mouse movements by writing to some buffers.

I'm not very familiar with it though. I think it may be better to ask around on some game hacking forum than here.

I'm trying to keep my distance to game hacking. I know my tools are used for it but it's not why I created them from the beginning.

Thanks for understanding and best wishes with your DMA project!
