### ISSUE TITLE
FTDI device reconnects randomly

### ISSUE THREAD

**Issue by haode333** [ufrisk/pcileech#221]
Had this weird issue happening for some time.
The FTDI FT601 USB Device will randomly disconnect and reconnect, and pcileech will get ```DEVICE: FPGA: ERROR: Unable to connect to USB/FT601 device [0,v0.0,0000]``` error.
Seems the only solution is to restart target system.

**Comment by ufrisk** [comment]
Hi,

I've noticed this as well some times on some hardware that the USB reconnects. I never was able to pinpoint the issue. I think it may have to do with excessive heat on the FTDI chip, the errors were reduced when putting a small heat sink on it on my ScreamerM2. On other hardware I never had any issues with it though so I'm not sure this would be the issue.

Also in firmware v4.11 I made some fixes with regards to the USB, that wouldn't exactly help against this issue, but it would hopefully more or less eliminate "Bad TLP" issues.

**Comment by haode333** [comment]
Hi Ufrisk,

Thanks for the answer. I also notice excessive heat and I guess that's the issue.
Would also love to try 4.11 when it comes out!

**Comment by ufrisk** [comment]
The v4.11 of the FPGA project has been out for a while.

**Comment by haode333** [comment]
> The v4.11 of the FPGA project has been out for a while.

was looking at the release tab, not paying attention to the commits. Will try it out!
Thanks again for your great work!

**Comment by haode333** [comment]
tried the new firmware & added some heatsink on Screamer but still experiencing this issue.
I checked with a thermometer and the temperature is only ~45 c. USB-C port is a little bit higher but I assume those chips are designed to work under this temperature.

**Comment by ufrisk** [comment]
Auch, so it's not your issue then.

I'm afraid I'm out of ideas what may be causing it then :\
