### ISSUE TITLE
DMA with OWC mercury helios 3s expansion problem?

### ISSUE THREAD

**Issue by viperr86** [ufrisk/pcileech#236]
Hey,
I have the OWC mercury helios 3s expension for my DMA for my laptop through TB4.
https://www.owc.com/solutions/mercury-helios-3s

All go smooth when i connect to laptop its show that the DMA is connected etc but when i do the DMA test it gives me blue screen right away and error stopcode: DRIVER_VERIFIER_DMA_VIOLATION

should be the correct driver but.
Im a Win11 user to

Thanks

**Comment by ufrisk** [comment]
See this thread: https://github.com/ufrisk/pcileech/issues/175

Also you may have to disable thunderbolt security and/or allow your device to do DMA in some thunderbolt settings in Windows and/or in BIOS.
