### ISSUE TITLE
MacOS

### ISSUE THREAD

**Issue by ZeroArrayCPP** [ufrisk/pcileech#239]
Will I be able to run MemProcFS on macOS?
I have a macbook air m1 and a Windows pc, I want to use the macbook to attack windows.

**Comment by ufrisk** [comment]
MemProcFS is currently not supported on macOS.

It's certainly possible to get it to run on macOS. I'm guessing it would be a medium sized job to get it to work, but I'd have to support it (which means testing for it in the future as well) and I'd also have to get myself a new macbook with the M1/M2 CPU to test on.

It's something I'd have to look into in the future, but right now I have other more prioritized items I'd need to finish up first. Unless someone decides to do a sponsored development we're looking at Q4 at the earliest.

I'll put it up as an enhancement suggestion to look into for the future. Many thanks for the suggestion 👍

**Comment by ZeroArrayCPP** [comment]
And thank you for the answer, ufrisk!
