### ISSUE TITLE
What does this output mean? 

### ISSUE THREAD

**Issue by ArcticSlayy** [ufrisk/pcileech#240]
C:\Users\Josh\Downloads\PCILeech_files_and_binaries_v4.15.3-win_x64-20230420>pcileech.exe display -min 0x1000 -device fpga -v

DEVICE: FPGA: ScreamerM2 PCIe gen2 x1 [300,25,500] [v4.10,0600] [ASYNC,NORM]
Memory Display: Contents for address: 0x0000000000001000
0000    e9 4d 06 00 01 00 00 00  00 00 00 00 3f 00 18 10   .M..........?...
0010    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0020    00 00 00 00 00 00 00 00  00 00 00 00 00 9b 20 00   .............. .
0030    00 00 00 00 00 00 00 00  ff ff 00 00 00 93 cf 00   ................
0040    00 00 00 00 00 00 00 00  ff ff 00 00 00 9b cf 00   ................
0050    00 00 00 00 00 00 00 00  00 10 ff cc 00 00 00 00   ................
0060    7c 16 00 00 30 00 da 16  00 00 10 00 00 00 00 00   |...0...........
0070    e0 59 77 29 05 f8 ff ff  00 70 00 80 d0 f7 ff ff   .Yw).....p......
0080    06 01 07 00 06 01 07 00  01 49 00 00 00 00 00 00   .........I......
0090    31 00 05 80 00 00 00 00  00 00 00 00 00 00 00 00   1...............
00a0    00 d0 1a 00 00 00 00 00  b8 0e 35 00 00 00 00 00   ..........5.....
00b0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
00c0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
00d0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
00e0    00 00 00 00 00 00 57 00  b0 af 51 86 01 e5 ff ff   ......W...Q.....
00f0    00 00 00 00 00 00 ff 0f  00 80 51 86 01 e5 ff ff   ..........Q.....

As per some recommendation, I was running this in the release version of this repo. After running is it normal to not allow anything else to run again? 
![image](https://github.com/ufrisk/pcileech/assets/64766174/c3052097-e55d-4302-9e9e-7a23fae36250)

**Comment by ArcticSlayy** [comment]
Like it worked originally which was just the downloaded zip of the binary release. However when I wanted to attempt probe I got unable to connect to device, so I re-tried this and it failed the second time.

**Comment by ArcticSlayy** [comment]
Edit, randomly after no changes it started working and I was able to probe,

**Comment by ufrisk** [comment]
Nice to see you got it to work 👍
