### ISSUE TITLE
Reading memory data update is slow

### ISSUE THREAD

**Issue by Monday-Leo** [ufrisk/pcileech#242]
Hi, I use the python api to read the memory through FPGA，the data is corroct and the speed is very high.
But the data read in almost one second are all the same just like picture shows.This means that although my reads are fast, the data I read is all the same.
In fact, the memory is dynamically changing, and it is impossible to keep the data unchanged within one second. What's wrong? How can i solve this problem?

![D@SF18WG5U8K)V79$%VM0B5](https://github.com/ufrisk/pcileech/assets/53975909/3be4e47b-ffb1-4812-bd1b-0b4f76adc2d3)

**Comment by ufrisk** [comment]
By default there is a data cache to speed things up. This gets partially cleared every second or so.

If you wish to avoid reading cached data there is a NOCACHE flag that you may use.

**Comment by Monday-Leo** [comment]
How can i set the NOCACHE flag in python api?
my code is like this:
```
vmm = memprocfs.Vmm(['-device', 'fpga'])
process_explorer = vmm.process('xxxxx.exe')
```

**Comment by Monday-Leo** [comment]
Oh, i guess i find it. is it right?
`process_explorer.memory.read(address,size,memprocfs.FLAG_NOCACHE)`

**Comment by Monday-Leo** [comment]
Yes,i have already solved the problem. It works well.

**Comment by ufrisk** [comment]
Awesome! Thanks for letting me know and best wishes with your DMA attacking.

Let me know if you should run into more issues or require addtional features in the API.
