### ISSUE TITLE
required HW for Closed-chassis usingThunderbolt or USB-C

### ISSUE THREAD

**Issue by Muhammd** [ufrisk/pcileech#243]
beside SCREAMER PCIE SQUIRREL(https://shop.lambdaconcept.com/home/50-screamer-pcie-squirrel.html) what other cable or Hardware is required to preform Closed-chassis DMA attack Testing using USB-C or thunderbolt port. testing will be done on new Intel/Dell and HP Laptops to validate if the Hardware and software protect prevent DMA Attack. we don't want to open the case to plugin the cable or card. need to preform closed-chassis testing.

**Comment by ufrisk** [comment]
USB is not DMA capable in that way. Thunderbolt is though. A eGPU chassis will work.

But Thunderbolt is usually quite well secured so I'd expect a plain DMA attack againt it to fail unless security been expicitly disabled by the user beforehand.

**Comment by Muhammd** [comment]
Thank you for quick response.
