### ISSUE TITLE
How to systematically learn these knowledge from beginning to end

### ISSUE THREAD

**Issue by wxblysk** [ufrisk/pcileech#244]
Hello author,
   I'am a student from china.My university major is Information Security.I am quite interested in computer hardware.Encouraged by your project, I have searched for many books and attempted to learn from scratch. But the results are not particularly good. I purchased an FPGA development board, but the textbooks on the market are very old and not suitable. May I ask if you could recommend some books or other suggestions for me as a beginner.
Best regards.Thx

**Comment by BLK434** [comment]
哥们我最近也在研究这个东西 方便加个V咱们一起交流交流吗 我自己是FPGA工程师

**Comment by ufrisk** [comment]
@wxblysk Thank you for your question. I apologize for the very slow answer. I usually get emails about new issues but it seems like not for this issue for some reason.

Anyhow, Documentation with regards to memory analysis with DMA is severely lacking.

It depends on what you wish to accomplish. If doing FPGA work and PCIe work there are documentations around this, tutorials etc, but it's a quite high learning curve.

If looking into memory analysis I usually recommend the art of memory forensics from the volatility people - it's old but in some areas it's nice. Also the Windows Internals books are nice.

But overall, I know it's extremely frustrating that there isn't one set of documentation, and that documentation is so fragmented. I have tried to do my best to document my tools in the wiki pages for the PCILeech, LeechCore and MemProcFS projects.

//Ulf
