### ISSUE TITLE
Learning about TLP Responses

### ISSUE THREAD

**Issue by MrCoInSanity** [ufrisk/pcileech#247]
Hello, I'm making this ticket about sending TLP responses via DMA, I just have some basic questions I hope you can answer...

1, Does the DMA send TLP responses and if so, how can I modify them?
2, How can I see TLP responses that are sent?
2, If it doesn't send TLP responses, do you have any idea how I can achieve this? Thanks in advance!

Finally I would like to apologise in advnace for my lack of knowledge and probably obvouse questions, 

thanks in advance!

**Comment by ufrisk** [comment]
1. Yes, DMA works by sending and receiving PCIe TLPs.
2. In PCILeech/MemProcFS add options: `-device fpga -vvv`. (Do it in PCILeech for simple requests, the printout will be massive if doing it with MemProcFS.
3. PCILeech have a `tlp` command wich allows you to send hand-crafted TLPs. Or use the `leechcorepyc` Python API.
