### ISSUE TITLE
Modifying pcileech config space

### ISSUE THREAD

**Issue by MrCoInSanity** [ufrisk/pcileech#248]
Hello, I hope you don't mind all the tickets I made regarding pcieleech, I promise ill calm down after this one haha.

Anyways, I was wondering why there is 2 config files with the same name, and it looks like they are the same inside... Do I modify both of these files? It would be amazing if you gave me an example of a test .coe file to see changes... Thanks in advance.

**Comment by ufrisk** [comment]
I'm closing this issue since I guess it was resolved.
