### ISSUE TITLE
need help on device

### ISSUE THREAD

**Issue by llxiaoyuan** [ufrisk/pcileech#250]
![image](https://github.com/ufrisk/pcileech/assets/36320938/01d54fcd-c14e-428b-bccd-f6c5a1996ec6)

i wonder
what is the green thing？and how to get it？

thanks in advance😊

**Comment by ufrisk** [comment]
It's an ExpressCard to PCIe adapter.

ExpressCard is predominantly found on older laptops, nowdays it's very rare, but it's excellent for DMA hotplug and works really well with DMA research.

You may find adapters on eBay or AliExpress and such sites.
