### ISSUE TITLE
fpga. pagedisplay/dump returns incorrect data.

### ISSUE THREAD

**Issue by eXskill** [ufrisk/pcileech#251]
Hello.
I'm trying to read a specific fragment from the memory of the target machine.
pcileech.exe pagedisplay -min 0x1520000 -device fpga -memmap auto
But the returned data does not match the real one, what could be the reason?

![image](https://github.com/ufrisk/pcileech/assets/42116821/9472057a-7320-4348-9a63-337610134a83)

**Comment by ufrisk** [comment]
Your HxD view show the offset from the base of your exe file.

Exe files are loaded into process virtual memory. In process virtual memory this address will be the randomized base address where the .exe is loaded _PLUS_ this offset you have in HxD.

Furthermore pcileech deals with physical memory. Not virtual memory. You'd first need to translate your virtual memory address into physical memory to view it like that. For that you'd have to traverse the page tables.

In my MemProcFS program you may view virtual memory directly in HxD. Open the memory.vmem file found under M:\name\<your_process_name>\memory.vmem

**Comment by eXskill** [comment]
Thanks a lot!
I didn't pay attention to the vmem/pmem extension.
