### ISSUE TITLE
USB-adapter shown in the readme?

### ISSUE THREAD

**Issue by InfiniteBSOD** [ufrisk/pcileech#258]
Hello,

Sorry for posting this since this isn't an issue w. Pcileech but been googling for hours trying to find the adapter depicted in the readme / main GitHub page for pcileech:
![Screenshot_20230901-214211.png](https://github.com/ufrisk/pcileech/assets/126592660/85dd2fec-46bc-4ecb-a727-95e48598d782)

All I find are eGPUs or PCIE that connects to mPCIE.

Would appreciate a link or a description what to search for.

Going to use pcileech on laptops and other devices that are running live and I don't have the possibility to insert a PCIE-card into so would really want that USB-adapter.

Best Regards

**Comment by ufrisk** [comment]
This is an ExpressCard to PCIe adapter. The name is PE3B. I don't think it's made any more, but there should be other combinations of adapters you may use.
