### ISSUE TITLE
Since new raspberry pi 5 now has PCIe interface, Can it be used as memory acqusition device in the future?

### ISSUE THREAD

**Issue by etapic** [ufrisk/pcileech#260]
Would be nice affordable alternative.

**Comment by ufrisk** [comment]
The RPi5 acts as host / root. To perform DMA attacks one would need a device that acts as device.

This means that the RPi5 would be unsuitable for DMA attacks.

The PCIe interface is quite interesting though, and maybe there will be a better business case to create a low-latency high-bandwidth PCIe to PCIe bridge device (basically replacing the USB endpoint with another PCIe endpoint). There would be a lot of work involved in this though so it may not be feasible.
