### ISSUE TITLE
PCILEECH: Failed to connect to the device.

### ISSUE THREAD

**Issue by Marsaaaaaaa** [ufrisk/pcileech#275]
Getting this error when using on target pc, remote works fine.
Card is a squirrel, 1st and 3rd led on.
Device shows as ethernet controller on local and usb controller on remote as it should.
Honestly have no idea what could be causing this, should I just try and flash the card with the latest firmware?

Not sure if it should look like this in device manager
![image](https://github.com/ufrisk/pcileech/assets/115399891/ebd03ff0-5d6b-4c09-bc12-db802cfeb3da)
![image](https://github.com/ufrisk/pcileech/assets/115399891/575491f6-234e-4b8e-a675-78f12df4543e)

**Comment by ufrisk** [comment]
No driver needs to be installed. It's normal that it looks like that on default firmware. DMA should work anyway.

**Comment by Marsaaaaaaa** [comment]
any idea why it wont work locally but just fine on remote?

**Comment by ufrisk** [comment]
have you connected the usb cable? even if the card is inserted in the same computer the usb cable need to be connected as well.

**Comment by Marsaaaaaaa** [comment]
oh wow cant believe my dumbass didnt try that, thanks lol
