### ISSUE TITLE
DEVICE: FPGA: ERROR: Unable to retrieve required Device PCIe ID [4,v4.12,0000]

### ISSUE THREAD

**Issue by tibi-atya** [ufrisk/pcileech#276]
HI Ulf,

I have the LambdaConcept Screamer Squirrel PCI sat on a TH3P4G3 GPU Dock Graphics Card Dock for Laptop Notebook Thunderbolt. 

I managed to flash the device to the latest bitstream last night however still have issues with DMA:

root@dfir:~# ./pcileech pcileech.exe display -min 0x1000 -device fpga -v

[+] using FTDI device: 0403:601f (bus 3, device 7)
[+] FTDIFTDI SuperSpeed-FIFO Bridge000000000001
DEVICE: FPGA: ERROR: Unable to retrieve required Device PCIe ID [4,v4.12,0000]
PCILEECH: Failed to connect to the device.
root@dfir:~# ./pcileech pcileech.exe display -min 0x1000 -device fpga -v

When the victim machine is turned off I get instead so I know that is is talking to the PCI card:
DEVICE: FPGA: ERROR: Unable to connect to USB/FT601 device [0,v0.0,0000]
PCILEECH: Failed to connect to the device.
root@dfir:~#
root@dfir:~#
root@dfir:~#
root@dfir:~# ./pcileech pcileech.exe display -min 0x1000 -device fpga -v

MY next move is to replace the GPU dock but do want something that can go into USB/Thunderbolt. 
Any ideas on that the issue is?

**Comment by ufrisk** [comment]
The USB communication to the device is working fine and its properly flashed.

There is however no PCIe connection to the target computer.

Try disabling Thunderbolt security (set it to legacy / no security in BIOS). Also disable IOMMU / VT-d in BIOS settings.

Let me know if you have some success with this.

**Comment by tibi-atya** [comment]
I never even though of the Thunderbolt protection, thanks man...

[+] using FTDI device: 0403:601f (bus 2, device 61)
[+] FTDIFTDI SuperSpeed-FIFO Bridge000000000001
DEVICE: FPGA: ScreamerM2 PCIe gen2 x1 [300,25,500] [v4.12,0700] [ASYNC,NORM]
Memory Display: Contents for address: 0x0000000000001000
0000    e9 4d 06 00 01 00 00 00  01 00 00 00 3f 00 18 10   .M..........?...
0010    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0020    00 00 00 00 00 00 00 00  00 00 00 00 00 9b 20 00   .............. .
0030    00 00 00 00 00 00 00 00  ff ff 00 00 00 93 cf 00   ................
0040    00 00 00 00 00 00 00 00  ff ff 00 00 00 9b cf 00   ................
0050    00 00 00 00 00 00 00 00  00 d0 95 7e 00 00 00 00   ...........~....
0060    7c 16 00 00 30 00 da 16  00 00 10 00 00 00 00 00   |...0...........
0070    50 95 df 07 03 f8 ff ff  00 80 00 00 b1 f7 ff ff   P...............
0080    06 01 07 00 06 01 07 00  01 09 00 00 00 00 00 00   ................
0090    33 00 05 80 00 00 00 00  00 00 00 00 00 00 00 00   3...............
00a0    00 d0 1a 00 00 00 00 00  78 06 37 00 00 00 00 00   ........x.7.....
00b0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
00c0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
00d0    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
00e0    00 00 00 00 00 00 57 00  b0 af 5f 52 00 a9 ff ff   ......W..._R....
00f0    00 00 00 00 00 00 ff 0f  00 80 5f 52 00 a9 ff ff   .........._R....

**Comment by ufrisk** [comment]
nice, I'm glad to see it works 👍 

also, when using Thunderbolt, it may be a good idea to use a memory map: https://github.com/ufrisk/LeechCore/wiki/Device_FPGA_AMD_Thunderbolt

I'm closing this issue since it's now resolved.

**Comment by tibi-atya** [comment]
Hi 

Sorry if this reopens this issue, everything is working good I can dump.

I have the latest DX3 driver in place but no matter what implant I use I get:

┌──(root㉿ilak)-[/home/tibi/Downloads/PCILeech_files_and_binaries_v4.17.5-linux_x64-20231128]
└─# ./pcileech -device fpga kmdload -kmd win10_x64    

[+] using FTDI device: 0403:601f (bus 1, device 13)
[+] FTDIFTDI SuperSpeed-FIFO Bridge000000000001
KMD: Failed. Error reading or interpreting memory #1.
PCILEECH: Failed to load kernel module.
                                                                                                                                                                   
┌──(root㉿ilak)-[/home/tibi/Downloads/PCILeech_files_and_binaries_v4.17.5-linux_x64-20231128]
└─# ./pcileech -device fpga kmdload -kmd win10_x64_2

[+] using FTDI device: 0403:601f (bus 1, device 13)
[+] FTDIFTDI SuperSpeed-FIFO Bridge000000000001
MemProcFS: Failed to initialize memory process file system in call to vmm.dll!VMMDLL_Initialize
KMD: Failed initializing required MemProcFS/vmm.dll
PCILEECH: Failed to load kernel module.
                                                                                                                                                                   
┌──(root㉿ilak)-[/home/tibi/Downloads/PCILeech_files_and_binaries_v4.17.5-linux_x64-20231128]
└─# ./pcileech -device fpga kmdload -kmd win10_x64_3

[+] using FTDI device: 0403:601f (bus 1, device 13)
[+] FTDIFTDI SuperSpeed-FIFO Bridge000000000001
MemProcFS: Failed to initialize memory process file system in call to vmm.dll!VMMDLL_Initialize
KMD: Failed initializing required MemProcFS/vmm.dll #1
PCILEECH: Failed to load kernel module.
                                                                                                                                                                   
┌──(root㉿ilak)-[/home/tibi/Downloads/PCILeech_files_and_binaries_v4.17.5-linux_x64-20231128]
└─# 


                   


┌──(root㉿ilak)-[/home/tibi/Downloads/PCILeech_files_and_binaries_v4.17.5-linux_x64-20231128]
└─# ./pcileech display -min 0x1000 -device fpga -v                                

[+] using FTDI device: 0403:601f (bus 1, device 13)
[+] FTDIFTDI SuperSpeed-FIFO Bridge000000000001
DEVICE: FPGA: ScreamerM2 PCIe gen2 x1 [300,25,500] [v4.12,0700] [ASYNC,NORM]
Memory Display: Failed reading memory at address: 0x0000000000001000.



┌──(root㉿ilak)-[/home/tibi/Downloads/PCILeech_files_and_binaries_v4.17.5-linux_x64-20231128]
└─# ./pcileech dump -min 0x0 -max 0x21e5fffff       

[+] using FTDI device: 0403:601f (bus 1, device 13)
[+] FTDIFTDI SuperSpeed-FIFO Bridge000000000001
Memory Dump: Initializing ... Done.
 Current Action: Dumping Memory                             
 Access Mode:    Normal                                                       
 Progress:       1104 / 8678 (12%)           
 Speed:          552 MB/s                        
 Address:        0x0000000145000000                      
 Pages read:     0 / 2221568 (0%)           
 Pages failed:   282624 (12%)                  
^C





Sorry this low level issue but once I have this down I should be set

After a reboot

──(root㉿ilak)-[/home/tibi/Downloads/PCILeech_files_and_binaries_v4.17.5-linux_x64-20231128]
└─# ./pcileech kmdload -kmd WIN10_X64  

[+] using FTDI device: 0403:601f (bus 1, device 22)
[+] 
[-] Cannot get chip configuration: Operation timed out
PCILEECH: Failed to connect to the device.

**Comment by ufrisk** [comment]
If your target is AMD or you're using this over Thunderbolt you must be using a memory map as described in the link I sent you above.

If not using the memory map things will most probably fail, and I don't see you using it in your examples above.

you can try on a freshly started system `./pcileech display -min 0x1000 -v` to see if DMA works at all. If it does your issues are likely related to the missing memmap. You may also try to use `-memmap auto` it may work if you're lucky, but best to use your own loaded from file (instructions in the link of my previous post).
