### ISSUE TITLE
Mouse&Keyboard status

### ISSUE THREAD

**Issue by HaunseerLin** [ufrisk/pcileech#289]
is there any way to get Game PC‘s “mouse & keyboard keypressing” in work PC？

**Comment by ufrisk** [comment]
Please understand that this project was not created for games. It was created as an infosec and forensics project and it still is even if it has become popular amongst games.

I'd prefer if discussions and questions about using it for games are done on other forums. If you google around you'll find plenty of discussions for at least the keyboard part on other forums like UnknownCheats.

Thanks for understanding and best wishes with your DMA project.
