### ISSUE TITLE
pci squirrel (Failed to connect to the device.)

### ISSUE THREAD

**Issue by ScHc4043** [ufrisk/pcileech#294]
Its not a firmware problem the lights are blinking when i turn on pc

**Comment by ScHc4043** [comment]
i fixed the problem but now i cant use pcileech

**Comment by ScHc4043** [comment]
DEVICE: FPGA: ERROR: Unable to connect to FPGA device [0,v0.0,0000]
PCILEECH: Failed to connect to the device.

**Comment by ScHc4043** [comment]
it gets disconnected like right after i plug it in

**Comment by ScHc4043** [comment]
i looked att device manager and went to the usb device it says the driver got configured and then the driver didnt start

**Comment by ufrisk** [comment]
The Github issues are for posting bugs and issues around the project. Not for general support. I'm closing this issue.

There is a step-by-step guide for looking into errors here: https://github.com/ufrisk/LeechCore/wiki/Device_FPGA_DMA_Not_Working it's a bit basic but it's what I would try at first at least.

You may also join the Discord and ask questions there in the help channel.
<a href="https://discord.gg/pcileech"><img src="https://discord.com/api/guilds/1155439643395883128/widget.png?style=banner3"/></a>
