### ISSUE TITLE
 Unable to retrieve required Device PCIe ID [4,v4.7,0000,FWCUST]

### ISSUE THREAD

**Issue by MarkosLEE** [ufrisk/pcileech#296]
I use the command:pcileech.exe display -min 0x1000 -device fpga -v
it outputs  :  Unable to retrieve required Device PCIe ID [4,v4.7,0000,FWCUST]
I have read all issue about this probelm ,but have no idea......
and I want to know how to flash the device to the bitstream.
hoping for your reply! thanks!

**Comment by MarkosLEE** [comment]
and I also have some success example,but maybe 200 try only 1 success..

**Comment by ufrisk** [comment]
The Github issues are a place to report potential bugs and come up with enhancement suggestions.

It's not a place to ask for general help with custom firmware. For that it's better to ask in the Discord channel. Hopefully you'll get help there.

<a href="https://discord.gg/pcileech"><img src="https://discord.com/api/guilds/1155439643395883128/widget.png?style=banner3"/></a>
