### ISSUE TITLE
AMD + Screamer PCIe Squirrel: Prode reads 10% then fails subsequently 

### ISSUE THREAD

**Issue by RampantDespair** [ufrisk/pcileech#297]
Hey there,

The issue is pretty much identical to #149 however with newer hardware.

CPU: AMD Ryzen 3600X
Motherboard: B450 Gaming Plus Max
DMA: Screamer PCIe Squirrel (https://docs.lambdaconcept.com/screamer/index.html)

```
 Memory Map:
 START              END               #PAGES
 0000000000000000 - 000000000009ffff  000000a0
 00000000000c0000 - 00000000ceffffff  000cef40

 Current Action: Probing Memory
 Access Mode:    Normal
 Progress:       33523 / 33523 (100%)
 Speed:          92 MB/s
 Address:        0x000000082F380000
 Pages read:     847840 / 8582016 (9%)
 Pages failed:   7734176 (90%)
Memory Probe: Completed.
```
Every `probe` after the first one (since boot) fail at 100% systematically.

I have disabled `IOMMU` as required per their "Getting Started" section.
And I am using the latest version of PCILeech (https://github.com/ufrisk/pcileech/releases/tag/v4.17)

Is this issue still a thing in relation to AMD and I must use dump or was a work around found since then?
Thanks for you time

**Comment by ufrisk** [comment]
Probe is super aggressive and will make things stop working on AMD. If you use any recent version of PCILeech there should be a warning message about it when you run it? Just never use probe on AMD.

Also on AMD you'd have to use a memmap, either -memmap auto or a manually put together memmap: https://github.com/ufrisk/LeechCore/wiki/Device_FPGA_AMD_Thunderbolt

The Github issues are for bug reports and enhancement requests. For general questions the Discord server is probably a better option.

<a href="https://discord.gg/pcileech"><img src="https://discord.com/api/guilds/1155439643395883128/widget.png?style=banner3"/></a>
