### ISSUE TITLE
PCILEECH: Failed to connect to the device.

### ISSUE THREAD

**Issue by anan1213095357** [ufrisk/pcileech#299]
PS D:\PCILeech_files_and_binaries_v4.18.0-win_x64-20240606> ./pcileech.exe display -min 0x1000 -device fpga -v

DEVICE: FPGA: ERROR: Unable to load 'FTD3XX.dll' or 'leechcore_driver.dll' [0,v0.0,0000]
PCILEECH: Failed to connect to the device.

75T

**Comment by ufrisk** [comment]
It literally says what the issue is in the error message. You need FTD3XX.DLL which is a separate download.

This is as instructed in the Installing part of the project readme at: https://github.com/ufrisk/pcileech?tab=readme-ov-file#installing-pcileech

**Comment by anan1213095357** [comment]
> It literally says what the issue is in the error message. You need FTD3XX.DLL which is a separate download.
> 
> This is as instructed in the Installing part of the project readme at: https://github.com/ufrisk/pcileech?tab=readme-ov-file#installing-pcileech

./pcileech.exe display -min 0x1000 -device fpga -v

DEVICE: FPGA: PCIeScreamer R1 PCIe gen2 x1 [500,0,1000] [v4.14,2200] [ASYNC,NORM,FWCUST]
Memory Display: Failed reading memory at address: 0x0000000000001000.

**Comment by ufrisk** [comment]
The github issues section isn't really meant for general help and connection issues. it's more for bug reports and enhancement suggestions.

but hop into the discord and ask for help:
<a href="https://discord.gg/pcileech"><img src="https://discord.com/api/guilds/1155439643395883128/widget.png?style=banner3"/></a>

or read up on the most common issues: https://github.com/ufrisk/LeechCore/wiki/Device_FPGA_DMA_Not_Working
