### ISSUE TITLE
Vmm Failed Probobly not enough Power or too much Power 

### ISSUE THREAD

**Issue by maxonrtx** [ufrisk/pcileech#307]
so last DMA i had there was a switch where i just changed it to usb and it worked i think the pci port give to much or not enough power to the DMA

**Comment by maxonrtx** [comment]
![image](https://github.com/user-attachments/assets/a3cd12e8-57b0-448d-9dee-d8eda2cd7693)
its connected but not working

**Comment by ufrisk** [comment]
That is not a supported DMA board.

Also, the Github issues sections are for issues and bugs with my free open source software, not for issues with various hardware vendors.

But you may get some answers if you ask in the Discord channel. Welcome there!

<a href="https://discord.gg/pcileech"><img src="https://discord.com/api/guilds/1155439643395883128/widget.png?style=banner3"/></a>
