### ISSUE TITLE
PCI Power to much or too Low

### ISSUE THREAD

**Issue by maxonrtx** [ufrisk/pcileech#308]
Hey i have a Problem so my old DMA Card had a Switch where the Power comes from the USB not PCI Because the PCI gives to much or to less Power now i have a new one and theres no switch and the DMA shows on the PC but Speedtest on 2 PC it says VMM Init Failed

**Comment by ufrisk** [comment]
Like I mentioned in the last issue this project issues section is about software issues in my software.

If you have issues with your hardware ask your hardware vendor about how to use it, or a replacement if it's broken, or if you ask around in the Discord someone in there may know what to do and help you.

I unfortunately do not know about your specific hardware and will be unable to answer.
