### ISSUE TITLE
IOMMU Bitlocker Recovery Keys

### ISSUE THREAD

**Issue by l4rm4nd** [ufrisk/pcileech#309]
Hi @ufrisk ,

many thanks for this very cool project.

I'm conducting a security analysis of a locked Windows 10/11 workstation. It's an HP EliteBook 650 G9 model.

The disk is full-encrypted using Bitlocker. However, no PBA is enabled and I have full access to the BIOS. So once the workstation is booted up, I am seeing the regular Windows lock screen.

I've started disabling security features within the BIOS such as:

- Disabling Virtualization Based BIOS Protection
- Trusted Execution Technology (TXT)
- Virtualization Technology (VTx); 
  - I've enabled this later on again when reading through the issues here on GitHub
- Virtualization Technology (VTd)
- DMA Protection

However, as soon as I disable TXT and VTd, I am greeted by the Bitlocker Recovery Key screen. TXT must be disabled in order to gain access to the VTd checkbox for disabling.

Am I correct that the DMA attack via Squirrle PCI will not work then?

I would likely have to conduct others attacks such as:

- [TPM sniffing](https://github.com/stacksmashing/pico-tpmsniffer)
- [Airstrike Attack](https://shenaniganslabs.io/2021/04/13/Airstrike.html)
- [Rogue DC](https://www.fitretech.com/blog/paranoia)

**Comment by ufrisk** [comment]
I think you only have to disabled the VT-d, but I'm unsure about the "DMA Protection" as well.

Usually bitlocker is not tripped if doing this, but it depends on how it's configured and the computer model.

**Comment by 5uck1ess** [comment]
Similarly, Dell Latitude 7000s or 9000s series will trigger BitLocker recovery if VT-d is disabled under a message that "Secure Boot policy has unexpectedly changed"

**Comment by ufrisk** [comment]
It's not always possible to disable it as mentioned here unfortunately. PCILeech might not always work.

**Comment by l4rm4nd** [comment]
Thanks for the feedback @ufrisk and @5uck1ess.

During my assessment I was not able to make use of PCILeech due to the aforementioned Bitlocker Recovery screen. I was not able to disable the security features within the BIOS without triggering this.

Cheers!

**Comment by l4rm4nd** [comment]
For future reference:

- https://www.youtube.com/watch?v=A5v67H7s0-8
- https://www.linkedin.com/posts/dlaskov_cybersecurity-windows-uefi-activity-7431764209559990272-m4zv

One can basically disable VTx completely in the BIOS without triggering Bitlocker recover key. One can also adjust DMA protection and set it to thunderbolt only. Won't trigger Bitlocker recovery as well. See YouTube video at 26m:37s.

Then we can execute a DMA pre-boot attack using an onboard M2 connector instead of Thunderbolt. As Thunderbolt is an external connector, is has more security baked in.

Helpful tools:

- https://github.com/PN-Tester/DMAReaper
- https://github.com/PN-Tester/FirstStrike
