### ISSUE TITLE
Why does PCILeech not work in hot-plug case?

### ISSUE THREAD

**Issue by hungphamz** [ufrisk/pcileech#35]
Hello.
Just like the title, when i using PCILeech via USB3380-EVB device in hot-plug case, it didnt work.
I tested on bold PC and laptop. It only works when USB3380-EVB plugged in machine from startup.
Did i miss something? thank you.

**Comment by ufrisk** [comment]
You don't mention which connecting method you use. 

Using ExpressCard in the Laptop almost always works. Using miniPCIe/M.2 in the laptop won't usually  work. Using standard PCIe in a desktop computer may work if lucky on some models.

It's just how things are. Sometimes it will work on some configs, on other configs it won't work. It's quite hardware and system dependent unfortunately.

**Comment by ufrisk** [comment]
Also, if your target system have a sleep mode, this one is usually quite nice. Sleep the laptop, plug in the hardware in the M.2 (or miniPCIe) slot and unsleep it. This usually works even if the target has bitlocker with pre-boot auth ...
