### ISSUE TITLE
Can't seem to mount file system

### ISSUE THREAD

**Issue by inushahapuarachchi** [ufrisk/pcileech#49]
Hi,
I just received my pcie screamer and everything is working so far and is quite stable.
For some reason I cannot load the file system.
I have installed DokanSetup.exe and rebooted. Is there something I am missing?

```
PS C:\Users\Monka\Downloads\pcileech-master\pcileech-master\pcileech_files> .\pcileech identify -device .\3.raw

IDENTIFY: Scanning to identify target operating system and page directories...
  Currently supported oprerating systems:
     - Windows (64-bit).
 Current Action: Windows System PageDirectoryBase/PML4 located
 Access Mode:    DMA (hardware only)
 Progress:       1536 / 2205 (69%)
 Speed:          109 MB/s
 Address:        0x0000000060100000
 Pages read:     393216 / 564544 (69%)
 Pages failed:   0 (0%)
IDENTIFY: Succeeded: Windows System page directory base is located at: 0x1ad002


PS C:\Users\Monka\Downloads\pcileech-master\pcileech-master\pcileech_files> .\pcileech mount -device .\2.raw -cr3 0x1ad003

MOUNT: INFO: FILES folder not mounted. (No kernel module loaded).
MOUNTING PCILEECH FILE SYSTEM:
===============================================================================
PCILeech Memory Process File System is mounted in the /proc/ folder.
Memory from dump files or PCILeech hardware DMA devices is analyzed to provide
a convenient process file system.
 - File system is read-only when dump files are used.
 - File system is read-write when FPGA hardware acquisition devices are used.
 - Full support exists for some x64 Windows operating systems.
 - Limited support for all other x64 operating systems.
===============================================================================
MOUNT: Mounting as drive K:\
MOUNT: Failed. Status Code: -7

```

**Comment by ufrisk** [comment]
dokan.h from dokany says:

```
/**
 * Dokan mount failed.
 * Requested an incompatible version.
 */
#define DOKAN_VERSION_ERROR -7
```

I guess you have a version mismatch in dokany. Can you please try to re-install the most recent version of it and reboot your computer before trying again?

**Comment by inushahapuarachchi** [comment]
thanks,

I have tried both
```
DokanSetup.exe
Dokan_x64.msi
```
from https://github.com/dokan-dev/dokany/releases/tag/v1.2.0.1000

I'll try some more

**Comment by hwvs** [comment]
pcileech is currently not updated with the latest dokan headers. If you install the complete dokany package you can copy the headers into the pcileech source and compile it - I did that and it worked for me.

**Comment by inushahapuarachchi** [comment]
Using older version also works.
https://github.com/dokan-dev/dokany/releases/tag/v1.1.0.2000

thank you

**Comment by ufrisk** [comment]
Hrm, it seems like they released the new version just a few days ago. too bad it starts failing and requires a recompile. Thanks for bringing this into my attention.

I'll update the headers to the new ones and recompile the binary at the same time when I release the PCILeech DLL that so many have been waiting for. Meanwhile the older version should work.

**Comment by inushahapuarachchi** [comment]
This one might not be related but..
It's not normal to see only an unknown_process-0 right?
I've tried mounting a 14gb dump & 2gb dump (with cr3 set) both don't show anything revealing
```
PS K:\> tree /F
Folder PATH listing for volume DOKAN
Volume serial number is 000000E1 1983:1116
K:.
│   liveram-native.raw
│
└───proc
    ├───pid
    │   └───0
    │       │   map
    │       │   name
    │       │   pid
    │       │   pml4
    │       │   vmem
    │       │
    │       ├───modules
    │       ├───virt2phys
    │       │       virt
    │       │       phys
    │       │       map
    │       │       page
    │       │       pt_pml4
    │       │       pt_pdpt
    │       │       pt_pd
    │       │       pt_pt
    │       │
    │       ├───vmemd
    │       └───.config
    │               cache_file_enable
    │               global_refresh_enable
    │               global_refresh_tick_period_ms
    │               global_refresh_read
    │               global_refresh_tlb
    │               global_refresh_proc_partial
    │               global_refresh_proc_total
    │
    └───name
        └───unknown_process-0
            │   map
            │   name
            │   pid
            │   pml4
            │   vmem
            │
            ├───modules
            ├───virt2phys
            │       virt
            │       phys
            │       map
            │       page
            │       pt_pml4
            │       pt_pdpt
            │       pt_pd
            │       pt_pt
            │
            ├───vmemd
            └───.config
                    cache_file_enable
                    global_refresh_enable
                    global_refresh_tick_period_ms
                    global_refresh_read
                    global_refresh_tlb
                    global_refresh_proc_partial
                    global_refresh_proc_total

PS K:\>
```

**Comment by ufrisk** [comment]
@inushahapuarachchi absolutely not related :)

this happens if you specify a cr3/pml4 belonging to a process - i.e. not the kernel cr3 - or it may have been some parsing error if you specified the kernel cr3 indeed.

basically it mounts a single generic x64 process (works on all x64 processes - linux/macOS ones too - if correct process cr3/pml4 is specified).

In your case I'm guessing it may be because you specified a slightly invalid cr3 - or possibly due to slightly corrupt memory dump if you specified the kernel page table base in the cr3 option. Are you able to mount without the cr3 option or with correct cr3 (3 zeros at end)

`.\pcileech mount -device .\2.raw`
`.\pcileech mount -device .\2.raw -cr3 0x1ad000`

**Comment by inushahapuarachchi** [comment]
I will try some more things before I report back but the above two did not fix it

**Comment by inushahapuarachchi** [comment]
Well I couldn't fix it (but then again I am no expert),
My system was using 2gb of ram.

It only ever "identified" the c3r 0x1ad002 in the 14gb section of pages (0x0000000100000000  and beyond) which doesn't make sense anyway.
Outside of this my pci leech setup is failing to find any sort of eprocess on its own nor any cr3 via the identify command 

```
PS C:\Users\Monka\Downloads\pcileech-master\pcileech-master\pcileech_files> .\pcileech probe

 Memory Map:
 START              END               #PAGES
 0000000000000000 - 000000000009ffff  000000a0
 00000000000c0000 - 0000000089efffff  00089e40
 0000000100000000 - 000000046e7fffff  0036e800

 Current Action: Probing Memory
 Access Mode:    DMA (hardware only)
 Progress:       23008 / (unknown)
 Speed:          187 MB/s
 Address:        0x000000059DFFF000
 Pages read:     4163296
 Pages failed:   1726752
PS C:\Users\Monka\Downloads\pcileech-master\pcileech-master\pcileech_files>
```

**Comment by ufrisk** [comment]
try dumping the memory to a file `pcileech.exe dump -max 0x46e7fffff -out <yourfilename>` and then run mount on the file. `pcileech.exe mount -device <yourfilename>`

**Comment by inushahapuarachchi** [comment]
No luck there
```
PS C:\Users\Monka\Downloads\pcileech-master\pcileech-master\pcileech_files> .\pcileech.exe dump -max 0x46e7fffff -out 10.raw

 Current Action: Dumping Memory
 Access Mode:    DMA (hardware only)
 Progress:       2224 / 18152 (12%)
 Speed:          52 MB/s
 Address:        0x000000008B000000
 Pages read:     564960 / 4646912 (12%)
 Pages failed:   4384 (0%)
Memory Dump: Failed. Cannot dump any sequential data in 16MB - terminating.
PS C:\Users\Monka\Downloads\pcileech-master\pcileech-master\pcileech_files> .\pcileech mount -device .\10.raw

MOUNT: INFO: FILES folder not mounted. (No kernel module loaded).
VmmProc: Unable to locate EPROCESS offsets.
VmmProc: Unable to auto-identify operating system for PROC file system mount.
         Please specify PageDirectoryBase (CR3/PML4) in the -cr3 option if value
         is known. If unknown it may be recoverable with command 'identify'.
MOUNT: INFO: PROC file system not mounted.
MOUNTING PCILEECH FILE SYSTEM:
===============================================================================
MOUNT: Mounting as drive K:\



```

**Comment by inushahapuarachchi** [comment]
Tried Windows 10 x64 Pro & Home editions on target - both have the same results

**Comment by inushahapuarachchi** [comment]
update:
worked when I force dumped the entire range which took quite the time..
```
PS C:\Users\Monka\Downloads\pcileech-master\pcileech-master\pcileech_files> .\pcileech dump -max 0x000000046dffffff -out
 full.raw -force

 Current Action: Dumping Memory
 Access Mode:    DMA (hardware only)
 Progress:       18144 / 18144 (100%)
 Speed:          9 MB/s
 Address:        0x000000046E000000
 Pages read:     4181728 / 4644864 (90%)
 Pages failed:   463136 (9%)
Memory Dump: Successful.
PS C:\Users\Monka\Downloads\pcileech-master\pcileech-master\pcileech_files> .\pcileech mount -device .\full.raw

MOUNT: INFO: FILES folder not mounted. (No kernel module loaded).
VMM: Skipping process due to parsing error.
     PML4: 0000000000000000 PID: 0 STATE: 0 EPROCESS: fffff8025383e078 NAME:
MOUNTING PCILEECH FILE SYSTEM:
===============================================================================
PCILeech Memory Process File System is mounted in the /proc/ folder.
Memory from dump files or PCILeech hardware DMA devices is analyzed to provide
a convenient process file system.
 - File system is read-only when dump files are used.
 - File system is read-write when FPGA hardware acquisition devices are used.
 - Full support exists for some x64 Windows operating systems.
 - Limited support for all other x64 operating systems.
===============================================================================
MOUNT: Mounting as drive K:\
```

**Comment by ufrisk** [comment]
Hello,

I'm glad it resolved itself.

You can also dump the first part of the memory (until PCILeech stops) to a file. Then append NULL bytes until the file is exactly 4GB big. Then dump the 2nd part of the memory with "pcileech dump -min 0x100000000" and append it. It will probably be faster.

About your other question with device IDs. It should work if you change them there. As an alternative to my scripts you can also rebuild the thing inside xilinx vivado.

Regards,
Ulf

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by inushahapuarachchi** [comment]
Thank you for your tips.
I appreciare it.
I will be using your code of virt2phys and display to write a library for reading virtual memory (given that you have cr3 and module base)

Sent from Blue<http://www.bluemail.me/r?b=13506>
On 19 Aug 2018, at 12:42, Ulf Frisk <notifications@github.com<mailto:notifications@github.com>> wrote:
Hello,

I'm glad it resolved itself.

You can also dump the first part of the memory (until PCILeech stops) to a file. Then append NULL bytes until the file is exactly 4GB big. Then dump the 2nd part of the memory with "pcileech dump -min 0x100000000" and append it. It will probably be faster.

About your other question with device IDs. It should work if you change them there. As an alternative to my scripts you can also rebuild the thing inside xilinx vivado.

Regards,
Ulf

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ufrisk** [comment]
Hi,

If coding things yourself you should really check out my DLL release which I'll release tomorrow or on Tuesday. It should handle quite a lot automatically and I hope it will be rather intuitive to use.

Regards,
Ulf

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ufrisk** [comment]
If coding things yourself you should really check out my DLL release which I'll release tomorrow or on Tuesday. It should handle quite a lot automatically and I hope it will be rather intuitive to use. Regards, Ulf

**Comment by inushahapuarachchi** [comment]
Can I ask if the reading functionality will be quick?
Either way understanding your already existing code is quite easy :)

Sent from Blue<http://www.bluemail.me/r?b=13506>
On 19 Aug 2018, at 23:54, Ulf Frisk <notifications@github.com<mailto:notifications@github.com>> wrote:
Hi,

If coding things yourself you should really check out my DLL release which I'll release tomorrow or on Tuesday. It should handle quite a lot automatically and I hope it will be rather intuitive to use.

Regards,
Ulf

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ufrisk** [comment]
Closing this issue as the original issue with the Dokany header versions is now resolved.

@inushahapuarachchi The DLL should have good performance. The settings towards the PCIeScreamer will however be quite conservative by default. The DLL however allows you to alter these settings to better suit your needs and characteristics of your system.
