### ISSUE TITLE
Who can sell me a USB3380-EVB board?

### ISSUE THREAD

**Issue by cofarmer** [ufrisk/pcileech#52]
It's hard to buy a USB3380-EVB board now. Somebody tell me how can i buy it?

**Comment by ufrisk** [comment]
I think the original supplier may have them back in stock. I'm not 100% sure about that though, but check it out.

**Comment by KimCalvin** [comment]
Where are you from? DM me on Twitter @KimCalviin

**Comment by cofarmer** [comment]
From HongKong,China

**Comment by KimCalvin** [comment]
@cofarmer if you are willing to pay the shipping we can figure something out. DM me.

**Comment by cofarmer** [comment]
What's your twitter？
