### ISSUE TITLE
pcileech dll for linux

### ISSUE THREAD

**Issue by fwdevv** [ufrisk/pcileech#54]
first of all the dll is working great on windows
do you have any hint on how to make the library work on linux?
Unfortunately I don't have any experience with dynamic/static libraries on linux
thanks for any help!

**Comment by ufrisk** [comment]
Thanks.

About Linux - I'm quite busy this coming month both at work and with preparing for a conference talk. I hope to find the time to look into this later in October. Hopefully it shouldn't be a massive undertaking and it will go smoothly. But it depends, I don't wish to promise anything.
