### ISSUE TITLE
[Issue] pcileech library : Freeze every ~5s

### ISSUE THREAD

**Issue by false** [ufrisk/pcileech#55]
Hello,

After a while at tracking this issue I found out it was coming from pcileech.
To explain my problem I will just describe the steps to reproduce :
- Make a simple console application that initialize the library 
- Read a ever changing value in a loop and print it in the console for exemple
-> it reads the correct result, but every now and then (around 5 seconds, my multiple debugger sessions shown a 5s period) it just freezes the whole app. The UC usage gets down to 0, and around 0.8s later it's back to work. Thing is I have 5 threads in my application, and it somehow affects every one of them ; That is also why I didn't notice it was pcileech the root of the problem.

You can test it with a read delay of 500 or 1, it won't change anything. Also put a Sleep(200) or so in your loop, it won't change anything. Every 5 seconds your application will freeze.

Any idea what the problem could be ? Is that an hardware problem or the lib that runs some routine every 5seconds ?

Thanks for your help, if you have any idea of what I could do please don't hesitate :-)

**Comment by ufrisk** [comment]
Yes, there is a housekeeping thread in there that once every 5 seconds will clear the page table cache (TLB) and do a partial refresh of the process list.
Once every 15 seconds a complete refresh will be performed.

https://github.com/ufrisk/pcileech/blob/master/pcileech/vmmproc.c#L1209

You may alter the timings around with this PCILeech_VmmConfigGet / PCILeech_VmmConfigSet in the DLL.

Please note however that the TLB refresh is quite important if your target process allocates new virtual memory. But you can try it around changing the values - but setting them too high may lead to problems.

===

As a general note the library is completely single-threaded at the moment. The internal housekeeping thread and all calls to the PCILeech_Vmm* functions compete for the same lock at the moment.

There is quite some potential for improving upon this; and this is something I plan to look into. But I have more pressing matters to look into so I'm not even sure it will be this year.

===

If you just need to check for a value without interruption I guess you can up time timings on this housekeeping thread and whenever you wish to do something else restore it to let it refresh before you do your other tasks...

**Comment by false** [comment]
Hi @ufrisk , thanks for the fast answer.
I may be wrong but I think I can't alter them directly through PCILeech_VmmConfigSet as I don't have access to the constants ; I will have a look to make it possible.

Anyway in a first step I have tested by changing hard coded value to much higher ones, and hourah it was indeed the root of my freezes! :-)

Thanks.
