### ISSUE TITLE
Anyone selling used Spartan-6 SP605 ?

### ISSUE THREAD

**Issue by Zibux** [ufrisk/pcileech#60]
I would gladly buy SP605 send a message to me if you have one.

And if anyone wants to buy used USB3380AB can sell that one too works perfect with pcileech.

**Comment by pimarplastics** [comment]
I have one

**Comment by ufrisk** [comment]
Please have a look at ebay.com or similar. The SP605 is widely available and it's not like the USB3380 which is a very special hardware that sold out earlier on.
