### ISSUE TITLE
VmmProcessGetModuleMap and VmmReadEx

### ISSUE THREAD

**Issue by bin5k** [ufrisk/pcileech#64]
I have problem in getting the module information (VmmProcessGetModuleMap) and using VmmReadEx, after i remote desktop in.

This problem also occurs in the example -> pcileech_dll_example
This happens after i login using remote desktop and wait like 10/20 mins.

VmmReadEx also fails to work properly

> PRESS ANY KEY TO CONTINUE ...
CALL:    PCILeech_VmmReadEx
SUCCESS: PCILeech_VmmReadEx
PRESS ANY KEY TO CONTINUE ...
CALL:    PCIleech_VmmProcess_GetSections #1
SUCCESS: PCIleech_VmmProcess_GetSections #1
         Count = 235
CALL:    PCIleech_VmmProcess_GetSections #2
SUCCESS: PCIleech_VmmProcess_GetSections #2
         #  NAME     OFFSET   SIZE     RWX
         =================================
PRESS ANY KEY TO CONTINUE ...
CALL:    PCIleech_VmmProcess_GetDirectories
SUCCESS: PCIleech_VmmProcess_GetDirectories
         #  NAME             OFFSET   SIZE
         =====================================
         00 EXPORT           00000000 00000000
         01 IMPORT           00000000 00000000
         02 RESOURCE         00000000 00000000
         03 EXCEPTION        00000000 00000000
         04 SECURITY         00000000 00000000
         05 BASERELOC        00000000 00000000
         06 DEBUG            00000000 00000000
         07 ARCHITECTURE     00000000 00000000
         08 GLOBALPTR        00000000 00000000
         09 TLS              00000000 00000000
         0a LOAD_CONFIG      00000000 00000000
         0b BOUND_IMPORT     00000000 00000000
         0c IAT              00000000 00000000
         0d DELAY_IMPORT     00000000 00000000
         0e COM_DESCRIPTOR   00000000 00000000
         0f RESERVED         00000000 00000000

My System is:
Windows 10 Pro (x64)
Version: 1803
OS build: 17134.345

**Comment by ufrisk** [comment]
Question: Are you targeting a memory dump, or are you using a hardware acquisition device? If so, PCIeScreamer, SP605?

Also: would it be possible to replicate this in such a way that you are able to provide a memory dump file that triggers the error? It would greatly speed up my ability to look into this and fix it.

**Comment by bin5k** [comment]
I'm using the AC701/FT601 (flashed with version 3.3) 
I will try to get more info on the error, it seems to happen 10-30 mins after i use the pcileech_dll_example a couple times.

The target system is using the same OS build i described above.

**Comment by ufrisk** [comment]
Can you please reflash to the 3.2 bitstream which may be more stable than the 3.3-beta bitstream and see if the problem persists.

I think I have experienced somewhat similar results before but never though much of it. When using it and then after a longer idle-time it stopped working until i power cycled the FPGA. But I would like to rule out any potential problems with the 3.3-beta bistream first.

**Comment by bin5k** [comment]
i have been using the 3.2 bitstream for last 2 days and the problem hasn't occurred yet, even after trying several times to replicate the error.
i'm gonna assume that problem is the 3.3-beta bitstream.

**Comment by ufrisk** [comment]
Awesome that the problem went away. I've marked the 3.3-beta version as not recommended a while ago. Please let me know if this problem arises again. I'm closing this issue now though.
