### ISSUE TITLE
Selling Hardware

### ISSUE THREAD

**Issue by ufrisk** [ufrisk/pcileech#69]
If looking to sell used PCILeech supported hardware please first try do so on sites like eBay.

If no success please post in this thread rather than creating new separate issues all the time.

**Comment by tornado240** [comment]
Selling PCIeScreamer, comes already flashed with PCILeech and also includes the jtag flasher. Message me if interested please

**Comment by ec2ae** [comment]
Selling SP605 Kit (Everything included). Already flashed. Message me if interested

**Comment by sp605** [comment]
> Selling SP605 Kit (Everything included). Already flashed. Message me if interested

I'm interested. Apparently github doesn't have a PM option so add me on discord at JustAGuy#7145 or email me at d0ccproof@protonmail.com. Thanks!

**Comment by Asdf144** [comment]
>           bump
> Still selling for 300€

would be interested

write me on Unknowncheats: asdf144

Thank you ;)

**Comment by tornado240** [comment]
Selling PCIe Screamer $100+shipping.

**Comment by ShaanCoding** [comment]
> Selling PCIe Screamer $100+shipping.

Hey, I'm interested in purchasing your PCIe Screamer, send me an email if it's still for sale

**Comment by olealgoritme** [comment]
I would like to buy if it's still available =) @tornado240
