### ISSUE TITLE
Software can detect PCIEScreamer?

### ISSUE THREAD

**Issue by helloboiss** [ufrisk/pcileech#70]
Is it possible that software can detect PCIEScreamer, with changed deviceID etc so it looks like an second GPU or WiFi ethernet. Can they dump memory to see it is a fake device?

**Comment by ufrisk** [comment]
Yes, it's possible to detect it due to other artifacts than DeviceID in the PCIe core. Also missing/non loaded drivers.

No, it's not possible for a driver to "look inside" the FPGA and dump it's memory (or programming).

**Comment by Maffelz** [comment]
In addition to that you could check the BARs and test if the devices behaves like expected.

**Comment by false** [comment]
> Yes, it's possible to detect it due to other artifacts than DeviceID in the PCIe core. Also missing/non loaded drivers.

Hi, what kind of other artifacts would we talk about here ?

**Comment by gcakir** [comment]
I would like to know what other artifacts are there as well.

**Comment by Waterman178** [comment]
> I would like to know what other artifacts are there as well.

The same question
