### ISSUE TITLE
flashing pciescreamer address error

### ISSUE THREAD

**Issue by tornado240** [ufrisk/pcileech#75]
Im getting this error when trying to flash my pcie screamer. I have tried flashing my own build and the prebuilt version. Using latest openocd on windows.

https://pastebin.com/gwMMt75r

**Comment by tornado240** [comment]
nvm, the LATEST version of openocd for windows (released in nov) doesnt work, had to use the previous one and it worked find

**Comment by ufrisk** [comment]
Thanks for the update. I'm glad the problem went away. Maybe log an issue for OpenOCD about this if they aren't already aware of it?
