### ISSUE TITLE
FPGA: Bad PCIe TLP received! Should not happen!

### ISSUE THREAD

**Issue by skullhornet** [ufrisk/pcileech#80]
I am using a SP605/FT601with a PCIe to M.2 Key adapter on a Laptop.
Pcileech is version 3.7.0 and the SP605 firmware is: 2.2
Host machine is Linux and target OS is Win 10.0.17134
VT-d is disabled in BIOS
If I stop the boot at the boot menu I am able to read memory.
However if I attempt to do the same on the Win 10 sign in screen I get a lot of these errors:

**Device Info: FPGA: Bad PCIe TLP received! Should not happen!**

Do you have any idea what might be causing this and a possible mitigation ?

**Comment by ufrisk** [comment]
Are you able to read memory at all - with as an example: `pcileech.exe display -min 0x1000` once it reaches the lock screen?

I know Microsoft have implemented some mitigations (which I haven't had time to look more closely into) in which they may disable bus-mastering on downstream bridges/switches when the lock screen is running. I don't believe this is your problem though since then it shouldn't work at all.

If you are able to read memory, but it's giving you bad TLPs my guess is a bad connection with low PCIe signal quality. Too many chained adapters or low quality PCIe cabling something like that. Or buggy PCILeech.

**Comment by skullhornet** [comment]
When the lock screen is active I get this: 
**Memory Display: Failed reading memory at address: 0x0000000000001000**
If I unlock the screen by entering the password I can successfully dump a page. 

I did a test with an Ubuntu live USB-stick and was able to successfully dump all of memory so the physical part is working OK. 

Any suggestions to where I should start looking ?

**Comment by ufrisk** [comment]
Then it seems to be related to the newer mitigations in Windows in which they disable the bus master on downstream bridges and ports on "new" devices when the computer is locked. I guess there shouldn't really be ways around it.

You can try to sleep the computer, plug in the device - power it on and then unsleep the device.
Alternatively try to use another port, I ideally the gfx card slot, I'm not sure their mitigation works if plugged into a port directly under the root complex.

But I haven't really have had time to do any testing myself of this.

**Comment by skullhornet** [comment]
By new devices do you mean devices which do not have a driver assigned to them ?
Thank you for the port tips but this is a laptop so my choice of ports are a bit limited :)

**Comment by ufrisk** [comment]
I have not looked closely into this relatively new mitigation yet so I can't really say.

**Comment by skullhornet** [comment]
Thank you for the quick response @ufrisk, much appreciated :)

**Comment by skullhornet** [comment]
I have been doing some more tests and discovered that I am able to read memory on the lock screen. 

For some strange reason pcileech seems to fail intermittently, consider the following: 

~/src/pcileech_files$ ./pcileech  display  -min 0x1000   -device FPGA

**Memory Display: Failed reading memory at address: 0x0000000000001000.**

~/src/pcileech_files$ ./pcileech  display  -min 0x1000   -device FPGA

**Memory Display: Failed reading memory at address: 0x0000000000001000.**

~/src/pcileech_files$ ./pcileech  display  -min 0x1000   -device FPGA

Memory Display: Contents for address: 0x0000000000001000
```
0000    e9 4d 06 00 01 00 00 00  01 00 00 00 3f 00 18 10   .M..........?...
0010    00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0020    00 00 00 00 00 00 00 00  00 00 00 00 00 9b 20 00   .............. .
```
snip...

Any idea what might be causing this timeout ? Are there any timeout parameters I can try to increase ?

**Comment by MAVProxyUser** [comment]
Did you ever solve this issue?

**Comment by MAVProxyUser** [comment]
Dies it have anything to do with the different types of signaling? 

"PCIe supports two kinds of interrupts: Legacy INTx and MSI" 
http://xillybus.com/tutorials/pci-express-tlp-pcie-primer-tutorial-guide-1

**Comment by ufrisk** [comment]
I'm pretty sure it's not related to INTx and MSI's. I've noticed this behavior myself but I haven't thought much about it; just rerun the commands 1-2 times and it will be OK.

I plan to look into a bunch of different issues related to the FPGA configuration for the next release though. Hopefully I'll be able to find out why that timeout is sometimes occurring as well.

**Comment by ufrisk** [comment]
The issues with "Bad PCIe TLP received" should now mostly be fixed, at least if running the Windows version of PCILeech. Closing issue.
