### ISSUE TITLE
How to get the memory size of target?

### ISSUE THREAD

**Issue by cofarmer** [ufrisk/pcileech#84]
How to get memory total size of target? So I can set the max address value.

**Comment by ufrisk** [comment]
it should be auto-detected in the most recent version. You can just start a dump and see the max address.

If you wish to set it manually you can do that still and it will override the auto-detect.

To manually find the max memory either use the auto-detect or use the probe command.

**Comment by cofarmer** [comment]
> it should be auto-detected in the most recent version. You can just start a dump and see the max address.
> 
> If you wish to set it manually you can do that still and it will override the auto-detect.
> 
> To manually find the max memory either use the auto-detect or use the probe command.

If start a patch, would it auto-detect?

**Comment by ufrisk** [comment]
Yeah, it should auto-detect when patching.

Patching is going to happen in a linear way right now from address 0 to address max

Dumping memory is changed so it first dumps memory above 4GB and then memory below 4GB. I haven't changed patching to this strategy yet, but it should be fine on most systems.

**Comment by CuriosoCat** [comment]
Hey @ufrisk, could i trouble you to explain how is the max memory is detected? Why is it greater than my physical RAM amount? Is this normal or part of pcileech's algorithm?

The max limit for my probes and dumps have been greater than the RAM installed in my system. e.g. 5856MB when i have 4GB RAM, 9192 MB when i have 8 GB RAM and 17384 MB when i have 16 GB RAM.

**Comment by ufrisk** [comment]
The address space is larger than the physical memory itself. There is usually a hole in between around 3-4 GB (depending on computer model) that is reserved for various memory mapped PCIe devices. If the whole in a given make is between 3-4GB exactly the amount of RAM (memory space) will be detected by PCILeech as 5GB. You'll still only have 4GB of memory and the hole will be zero-padded.

PCILeech auto-detects the amount of memory by reading small chunks of memory in a fairly optimal pattern.

**Comment by CuriosoCat** [comment]
Thanks for the quick reply @ufrisk 😄 

**So to check if I understand this correctly:**
There are reserved memory regions, aka "holes", that are for memory mapped PCIe devices which are in between the 3GB and 4GB region.

If the holes are within the 3GB-4GB, PCILeech accounts for this by increasing the max memory limit to account for the space taken up by the holes? For example, in my case, there seems to be an extra 1760 MB on top of the RAM sizes, i.e.:

- (4GB RAM) 4096 + 1760 = 5856 MB

- (8GB RAM) 8192 + 1760 = 9192 MB

So this extra 1760 MB is then the total size of the holes which cannot be read via DMA with PCILeech and will be zero-padded? Do these holes correspond to the pages that were failed to be read when i use **pcileech probe/dump**?

**Comment by ufrisk** [comment]
Correct. Those holes should roughly correspond with the failed pages. Also PCILeech will fail to read "ordinary" physical memory that is used by things like SMM and CSME and that are mapped away from DMA.

**Comment by cofarmer** [comment]
@ufrisk My computer is 4G RAM, sometime unlock succeed (patched) in 4G+ address, so it's zero between 4-5G RAM

**Comment by cofarmer** [comment]
@ufrisk My computer is 4G RAM, sometime unlock succeed (patched) in 4G+ address, so it's not zero between 4-5G RAM

**Comment by ufrisk** [comment]
exactly, since unavailable zero-padded regions are mostly in the addressable region between 3-4 GB that means there are memory on your 4GB stick that will end up addressable above 4GB.
super simplified:
physical address 0-3GB = region 0-3GB of your RAM.
physical address 3-4GB = "PCIe device addressing" / zero-padded by PCILeech
physical address 4-5GB = region 3-4GB of your RAM.
