### ISSUE TITLE
Pcileech and LeechCore on Android

### ISSUE THREAD

**Issue by xssuser** [ufrisk/pcileech#86]
I want to compile pcileech and LeechCore on Android to connect my pciescreamer。

1.How to compile them?

2.What drives does pciescreamer need to connect to Android phones via OTG?

**Comment by ufrisk** [comment]
Android support was removed in the 4.0 release. It wasn't widely used and for me it was a support burden.

It may be possible to check out the earlier pcileech build instructions in releases 3.x and modify them for Android.
