### ISSUE TITLE
Can't read memory with thunderbolt（USB-C port）!

### ISSUE THREAD

**Issue by cofarmer** [ufrisk/pcileech#87]
Can't read memory with thunderbolt 3（Type-C port）, and the target OS is Windows 7。

After run pcileech testmemread -min 0x1000, the output is:
Memory Test Read: starting, reading 1000 times from address: 0x00001000
Memory Test Read: Failed. DMA failed / data changed by target computer / memory corruption. Read: 0. Run: 0. Offset: 0x000

**Comment by cofarmer** [comment]
When set the -min as 0x1000, failed always. When set the -min as 0x100000 or 0x10000000 ...., it succeed. And if failed once during reading memory, failed bellow always.

**Comment by ufrisk** [comment]
By the looks of it address 0x100000 is readable on your system, but not address 0x1000 for some reason related to your target system.

When the USB3380 encounters unreadable memory it most often freezes until power cycled unfortunately.

This is a particularity with your target system and the USB3380 hardware. Unfortunately I'm not able to fix this in software. It's just how things are.

**Comment by cofarmer** [comment]
Not USB3380, what i used was SP605+FT601 board.
