### ISSUE TITLE
PCILEECH: Failed to connect to the device

### ISSUE THREAD

**Issue by gcakir** [ufrisk/pcileech#90]
Greetings,

I installed PCIeScreamer into the target computer. After I boot into Windows 10:
Led2 is blinking continuosly (green),
Led1 is off,
Led3 is on (green).

There is another led (which is RED) on the left-hand side and it is constantly on in red color.

I receive the following error when I input "pcileech probe":
PCILEECH: Failed to connect to the device.

When I input "pcileech display -v", I get "PCILEECH: Failed to connect to the device." error again.

- I tried these inputs both on the target and on the computer to which the USB cable is connected. I always get these errors.
- I changed PCIe slot. It didn't help.
- I tried different USB cables (both 3.0 Micro and Mini 5) which came along with PCIeScreamer, still the same error.

My motherboard is Gigabyte Z390 Aorus Master. I also updated my motherboard's BIOS. It didn't help.

Is it somehow incompatible with my motherboard? What am I doing wrong here?

Thank you very much in advance!

**Comment by ufrisk** [comment]
Hi,

Have you flashed the correct PCILeech FPGA bitstream as described on https://github.com/ufrisk/pcileech-fpga/tree/master/pciescreamer

The continuous blinking suggests that you may have the LambdaConcent bistream flashed - which is incompatible with PCILeech. Once you think you have it correctly flashed try press the button described on the above info page to see if a Led then blinks.

**Comment by gcakir** [comment]
Thank you very much @ufrisk.
I was so excited when I first received the board, I didn't even properly read the description. I hadn't flashed it before I tried using it. I am sorry! I was stupid.

However, I have now another problem. When I am flashing, I receive the following error:

```
device needs paging or 4-byte addresses - not implemented
contents differ
```

I receive that error even tough I applied the git patch into OpenOCD as described in this link: http://blog.lambdaconcept.com/doku.php?id=products:jtagserial_programmer

I am sure that the patch has been successfully applied because I can see the changes in the source file. After applying the patch I used following commands to compile OpenOCD as described in the link:

```
make
sudo make install
```
I am sure I did everything according to your your descriptions and the descriptions in LambdaConcept's Wiki.

**Another important thing I should mention:**
In your readme.md it says:

> Please also note that the DIP-switch SW2 should be configured as: 1: ON, 2: OFF, 3: OFF.

But on my board there is **no DIP-switch SW2**. Here is a picture of my board:
![image](https://user-images.githubusercontent.com/19774563/57809813-9c0d5600-7766-11e9-89ee-b051f3599c23.png)

The picture on LambdaConcept's website also does not show any DIP-switch SW2.
http://blog.lambdaconcept.com/lib/exe/fetch.php?cache=&w=900&h=764&tok=979dac&media=products:r02_01_cut.jpeg

![image](https://user-images.githubusercontent.com/19774563/57809440-c3175800-7765-11e9-9be1-acbdc5ffe53d.png)

Could this also be a reason for the problem? Or should this be any cause of concern?

**Comment by gcakir** [comment]
@ufrisk 
OK. I solved the issue.
I purchased an JTAG-HS2 cable and flashed it with Vivado Tcl Shell.
It flashed successfully!

The PCIeScreamer was always installed into PCIe X1 slot and I still could not connect the target computer from another computer.

This time, I moved PCIeScreamer to X16 slot and it worked!
