### ISSUE TITLE
PcieScreamerR02: 100% pages failed

### ISSUE THREAD

**Issue by arisada** [ufrisk/pcileech#93]
I am using PcieScreamer R02 to evaluate the security of a laptop. I've tried several configurations and I always get negative results. Always trying with a user logged in.

* WIN 10 Laptop with TPM-based bitlocker with Thunderbolt3, Thunderbolt3 to PCI, 8G RAM:
pcileech fails to connect with the device most of the time. When it doesn't, I get this output from pcileech probe:
```
 Current Action: Probing Memory                             
 Access Mode:    Normal                                                       
 Progress:       8192 / 8192 (100%)           
 Speed:          282 MB/s                        
 Address:        0x0000000200000000                      
 Pages read:     0 / 2097153 (0%)           
 Pages failed:   2097153 (100%)                  
Memory Probe: Completed.
```

* Win 10 Desktop with bitlocker (password), pciescreamer in Motherboard's PCIe port, virtualization disabled in BIOS, 16G RAM:
```
aris@ubuntu1404:~/pcie/pcileech-4.1/files$ ./pcileech probe -device fpga

 Memory Map:                                     
 START              END               #PAGES   
                                                 
                                                 
 Current Action: Probing Memory                             
 Access Mode:    Normal                                                       
 Progress:       4096 / 4096 (100%)           
 Speed:          273 MB/s                        
 Address:        0x00000000FFFFF000                      
 Pages read:     0 / 1048576 (0%)           
 Pages failed:   1048576 (100%)                  
Memory Probe: Completed.
```

However, the same command succeeds during the bitlocker's password prompt:

```
aris@ubuntu1404:~/pcie/pcileech-4.1/files$ ./pcileech probe -device fpga

 Memory Map:                                     
 START              END               #PAGES   
 fffffffffffff000 - 000000000009efff  000000a0   
 00000000000bf000 - 00000000bf7fefff  000bf740   
 00000000fffff000 - 00000001a34a6fff  000a34a8   
                                                            
 Current Action: Probing Memory                                               
 Access Mode:    Normal                                                       
 Progress:       13936 / 17392 (80%)             
 Speed:          278 MB/s                                
 Address:        0x0000000366FFF000                      
 Pages read:     1453192 / 4452352 (32%)           
 Pages failed:   2114424 (47%)                  
^C
```

My various other attempts on other laptops (through mini-pcie and M2) haven't been more successful. At this point I don't know what to do anymore. Any suggestion ?

Thanks,

Aris

**Comment by arisada** [comment]
Update: It worked on the desktop after I tried a different cpie port. I still don't know why it fails through thunderbolt.

**Comment by ufrisk** [comment]
Hardware vendors and Microsoft have done a pretty good job in securing Thunderbolt recently.

Usually you have to set the Thunderbolt security mode to "Legacy" or "No Security" in BIOS for it to work at all - and then only by default on non-thunderbolt security aware OS'es. Regardless of BIOS settings more recent Windows 10 versions should be secure with regards to Thunderbolt.

**Comment by arisada** [comment]
Thanks for you update. I didn't see any "thunderbolt security" item in the bios, but it might be hidden in some other security item.

I've had more success on the target system, by plugging in place of the WiFi mpcie card. It scans up to 10% of the memory before failing. I still have to regularly restart computer because the the pci device isn't detected anymore, or I get the "Failed to connect to the device" error, but if it worked once on limited memory, maybe it will work again with different `-min` parameters.

**Comment by ufrisk** [comment]
You'll have to try around. sometimes the target system freezes if the PCIeScreamer reads some firmware memory segment. Or if the pcie link is unstable the PCIeScreamer will lose connection.

If using the ribbon cables to connect to the wifi slot use the shortest possible one for better signal quality and stability. The PCIeScreamer R02 is fairly stable, but still the xilinx dev boards are slightly more stable.

**Comment by arisada** [comment]
I unfortunately have to use long ribbons. I'll investigate if I can reduce their length and/or shield them. Is there a way to make pcileech go slower to avoid stability issues ?

Thanks
```
aris@ubuntu1404:~/pcie/pcileech-4.1/files$ ./pcileech patch -sig unlock_win10x64 -min 0x100000000

 Current Action: Patching                             
 Access Mode:    Normal                                                       
 Progress:       3400 / 6120 (55%)           
 Speed:          100 MB/s                        
 Address:        0x00000001D486C000                      
 Pages read:     82 / 1566720 (0%)           
 Pages failed:   870426 (55%)                  
^C
```

**Comment by ufrisk** [comment]
Yes, it should be possible to force PCIe gen1, but I'm not sure it's working, I either have a bug in my code or more likely an error in documentation. Also

Can you please try `./pcileech -v -vv -device fpga://1 patch -sig unlock_win10x64 -min 0x100000000`

Also you could alter some timing values in the `-device fpga://1:xxx:xxx:xxx` but if you use a long ribbon cable unfortunately stability problems are likely to persist no matter what you do.

If it says something with PCIe gen1 it's probably working, but I'll look more closely into this and either update code or documentation - unfortunately this coming weekend.

**Comment by arisada** [comment]
Thanks for the suggestions. I have this output:

```
aris@ubuntu1404:~/pcie/pcileech-4.1/files$ ./pcileech -v -vv -device fpga://1 patch -sig unlock_win10x64 -min 0x100000000

DEVICE: FPGA: PCIeScreamer R2 PCIe gen1 x1 [400,0,750] [v3.4,0200]
Successfully loaded LeechCore v1.2.0 Device 3
 Memory Map:                                     
 START              END               #PAGES   
 0000000100000000 - 00000001764b3fff  000764b4   
 00000001764d0000 - 00000001764d0fff  00000001   
                                                      
 Current Action: Patching                                                     
 Access Mode:    Normal                                                       
 Progress:       6119 / 6120 (99%)              
 Speed:          68 MB/s                                 
 Address:        0x000000027E7FF000                      
 Pages read:     484533 / 1566720 (30%)           
 Pages failed:   1082186 (69%)                  
Patch: Failed. No signature found.
```

I've seen substantial improvements since I moved to the shorter ribbon and after I "shielded" them (tin foil). I still haven't found the approximate location for the injection but it's just a matter of time before I find it.

**Comment by ufrisk** [comment]
Thanks for the update and good luck :)

About the unlock signature, it's a binary signature that may change or break in updates. I haven't checked it out since March so it may or may not work.

**Comment by arisada** [comment]
The signature didn't work, but I managed to get to the target with KMD + wx64_pscmd. wx64_unlock is failing with 0x80004005. Since KMD is putting less stress on the pcie bus, it's much more reliable.

Thanks for your help !

**Comment by ufrisk** [comment]
Thanks for the update. I'm glad to see everything turned out well in the end.

And yeah, I'll try to find the time to update those unlock signatures ...
