### ISSUE TITLE
PC not finding Screamer

### ISSUE THREAD

**Issue by Milion22** [ufrisk/pcileech#94]
Hey. So I bought a Screamer R02 that arrived today but when I plugged it in nothing happened. It wont show up in BIOS and zero of the LEDs are lighting up. I have tried it in 2 different computers, all slots and both show the same result. I haven't flashed it yet since I can't figure out the process right now as I have the Lambda cable. Is there a way to test if I have received a dead card? or if you got anything I can try to get it to work? I appreciate anything to try at this point. 

Hälsningar.

**Comment by ufrisk** [comment]
It's supposed to at least show a red LED when it's powered on.

But it may be powered either from PCIe or the barrel jack on the top of the board. You may select the power source with a jumper. Mbe it's just in the wrong position? https://gist.githubusercontent.com/ufrisk/c5ba7b360335a13bbac2515e5e7bb9d7/raw/e4e9ae4bf5fe0f723d6afe30703ac97df7e2c905/__gh_pciescreamer2.jpg (see power source select jumper at the upper left of the board)

**Comment by Milion22** [comment]
Holy god you saved it for me. It works perfectly now after switching the jumper spot, must have been set on external power source. 

As a fellow Swede I wish you en glad midsommar och skål.
